import type { CurrencyDefinition } from "./types";

/** Generated registry cache. Source dataset is generated from ISO 4217 and Unicode CLDR. */
export const CURRENCY_REGISTRY_VERSION = "2026-09";
export const CURRENCY_REGISTRY: readonly CurrencyDefinition[] = [
  {
    code: "AED",
    name: "United Arab Emirates Dirham",
    nativeName: "درهم إماراتي",
    symbol: "AED",
    nativeSymbol: "د.إ.",
    numericCode: "784",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "AFN",
    name: "Afghan Afghani",
    nativeName: "افغانۍ",
    symbol: "؋",
    nativeSymbol: "؋",
    numericCode: "971",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "ALL",
    name: "Albanian Lek",
    nativeName: "Leku shqiptar",
    symbol: "ALL",
    nativeSymbol: "Lekë",
    numericCode: "008",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "AMD",
    name: "Armenian Dram",
    nativeName: "հայկական դրամ",
    symbol: "֏",
    nativeSymbol: "֏",
    numericCode: "051",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "ANG",
    name: "Netherlands Antillean Guilder",
    nativeName: "Nederlands-Antilliaanse gulden",
    symbol: "ANG",
    nativeSymbol: "NAf.",
    numericCode: "532",
    minorUnit: 2,
    status: "historical",
    source: "ISO4217+CLDR"
  },
  {
    code: "AOA",
    name: "Angolan Kwanza",
    nativeName: "kwanza angolano",
    symbol: "Kz",
    nativeSymbol: "Kz",
    numericCode: "973",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "ARS",
    name: "Argentine Peso",
    nativeName: "peso argentino",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "032",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    nativeName: "Australian Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "036",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "AWG",
    name: "Aruban Florin",
    nativeName: "Arubaanse gulden",
    symbol: "AWG",
    nativeSymbol: "Afl.",
    numericCode: "533",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    nativeName: "Azərbaycan Manatı",
    symbol: "₼",
    nativeSymbol: "₼",
    numericCode: "944",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BAM",
    name: "Bosnia-Herzegovina Convertible Mark",
    nativeName: "Bosanskohercegovačka konvertibilna marka",
    symbol: "KM",
    nativeSymbol: "KM",
    numericCode: "977",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BBD",
    name: "Barbadian Dollar",
    nativeName: "Barbadian Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "052",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    nativeName: "বাংলাদেশী টাকা",
    symbol: "৳",
    nativeSymbol: "৳",
    numericCode: "050",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    nativeName: "دينار بحريني",
    symbol: "BHD",
    nativeSymbol: "د.ب.",
    numericCode: "048",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BIF",
    name: "Burundian Franc",
    nativeName: "franc burundais",
    symbol: "BIF",
    nativeSymbol: "FBu",
    numericCode: "108",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BMD",
    name: "Bermudan Dollar",
    nativeName: "Bermudian Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "060",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BND",
    name: "Brunei Dollar",
    nativeName: "Dolar Brunei",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "096",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BOB",
    name: "Bolivian Boliviano",
    nativeName: "boliviano",
    symbol: "Bs",
    nativeSymbol: "Bs",
    numericCode: "068",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BOV",
    name: "Bolivian Mvdol",
    nativeName: "MVDOL boliviano",
    symbol: "BOV",
    nativeSymbol: "BOV",
    numericCode: "984",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    nativeName: "Real brasileiro",
    symbol: "R$",
    nativeSymbol: "R$",
    numericCode: "986",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BSD",
    name: "Bahamian Dollar",
    nativeName: "Bahamian Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "044",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BTN",
    name: "Bhutanese Ngultrum",
    nativeName: "དངུལ་ཀྲམ",
    symbol: "BTN",
    nativeSymbol: "Nu.",
    numericCode: "064",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BWP",
    name: "Botswanan Pula",
    nativeName: "Botswanan Pula",
    symbol: "P",
    nativeSymbol: "P",
    numericCode: "072",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BYN",
    name: "Belarusian Ruble",
    nativeName: "беларускі рубель",
    symbol: "BYN",
    nativeSymbol: "Br",
    numericCode: "933",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "BZD",
    name: "Belize Dollar",
    nativeName: "Belize Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "084",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    nativeName: "Canadian Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "124",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "CDF",
    name: "Congolese Franc",
    nativeName: "franc congolais",
    symbol: "CDF",
    nativeSymbol: "FC",
    numericCode: "976",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "CHE",
    name: "WIR Euro",
    nativeName: "WIR-Euro",
    symbol: "CHE",
    nativeSymbol: "CHE",
    numericCode: "947",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    nativeName: "Schweizer Franken",
    symbol: "CHF",
    nativeSymbol: "CHF",
    numericCode: "756",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "CHW",
    name: "WIR Franc",
    nativeName: "WIR Franken",
    symbol: "CHW",
    nativeSymbol: "CHW",
    numericCode: "948",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "CLF",
    name: "Chilean Unit of Account (UF)",
    nativeName: "unidad de fomento chilena",
    symbol: "CLF",
    nativeSymbol: "CLF",
    numericCode: "990",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "CLP",
    name: "Chilean Peso",
    nativeName: "Peso chileno",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "152",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    nativeName: "人民币",
    symbol: "¥",
    nativeSymbol: "¥",
    numericCode: "156",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "COP",
    name: "Colombian Peso",
    nativeName: "peso colombiano",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "170",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "COU",
    name: "Colombian Real Value Unit",
    nativeName: "Colombian Real Value Unit",
    symbol: "COU",
    nativeSymbol: "COU",
    numericCode: "970",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "CRC",
    name: "Costa Rican Colón",
    nativeName: "colón costarricense",
    symbol: "₡",
    nativeSymbol: "₡",
    numericCode: "188",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "CUP",
    name: "Cuban Peso",
    nativeName: "peso cubano",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "192",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "CVE",
    name: "Cape Verdean Escudo",
    nativeName: "escudo cabo-verdiano",
    symbol: "CVE",
    nativeSymbol: "CVE",
    numericCode: "132",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    nativeName: "česká koruna",
    symbol: "Kč",
    nativeSymbol: "Kč",
    numericCode: "203",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "DJF",
    name: "Djiboutian Franc",
    nativeName: "franc djiboutien",
    symbol: "DJF",
    nativeSymbol: "Fdj",
    numericCode: "262",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "DKK",
    name: "Danish Krone",
    nativeName: "dansk krone",
    symbol: "kr",
    nativeSymbol: "kr.",
    numericCode: "208",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "DOP",
    name: "Dominican Peso",
    nativeName: "peso dominicano",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "214",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "DZD",
    name: "Algerian Dinar",
    nativeName: "دينار جزائري",
    symbol: "DZD",
    nativeSymbol: "د.ج.",
    numericCode: "012",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "EGP",
    name: "Egyptian Pound",
    nativeName: "جنيه مصري",
    symbol: "E£",
    nativeSymbol: "E£",
    numericCode: "818",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "ERN",
    name: "Eritrean Nakfa",
    nativeName: "ኤርትራዊ ናቕፋ",
    symbol: "ERN",
    nativeSymbol: "Nfk",
    numericCode: "232",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "ETB",
    name: "Ethiopian Birr",
    nativeName: "የኢትዮጵያ ብር",
    symbol: "ETB",
    nativeSymbol: "ብር",
    numericCode: "230",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "EUR",
    name: "Euro",
    nativeName: "euro",
    symbol: "€",
    nativeSymbol: "€",
    numericCode: "978",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "FJD",
    name: "Fijian Dollar",
    nativeName: "Fijian Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "242",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "FKP",
    name: "Falkland Islands Pound",
    nativeName: "Falkland Islands Pound",
    symbol: "£",
    nativeSymbol: "£",
    numericCode: "238",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "GBP",
    name: "British Pound",
    nativeName: "British Pound",
    symbol: "£",
    nativeSymbol: "£",
    numericCode: "826",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "GEL",
    name: "Georgian Lari",
    nativeName: "ქართული ლარი",
    symbol: "₾",
    nativeSymbol: "₾",
    numericCode: "981",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "GHS",
    name: "Ghanaian Cedi",
    nativeName: "Ghanaian Cedi",
    symbol: "GH₵",
    nativeSymbol: "GH₵",
    numericCode: "936",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "GIP",
    name: "Gibraltar Pound",
    nativeName: "Gibraltar Pound",
    symbol: "£",
    nativeSymbol: "£",
    numericCode: "292",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "GMD",
    name: "Gambian Dalasi",
    nativeName: "Gambian Dalasi",
    symbol: "GMD",
    nativeSymbol: "D",
    numericCode: "270",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "GNF",
    name: "Guinean Franc",
    nativeName: "franc guinéen",
    symbol: "FG",
    nativeSymbol: "FG",
    numericCode: "324",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "GTQ",
    name: "Guatemalan Quetzal",
    nativeName: "quetzal",
    symbol: "Q",
    nativeSymbol: "Q",
    numericCode: "320",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "GYD",
    name: "Guyanese Dollar",
    nativeName: "Guyanese Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "328",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    nativeName: "港元",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "344",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "HNL",
    name: "Honduran Lempira",
    nativeName: "lempira hondureño",
    symbol: "L",
    nativeSymbol: "L",
    numericCode: "340",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "HTG",
    name: "Haitian Gourde",
    nativeName: "gourde haïtienne",
    symbol: "HTG",
    nativeSymbol: "G",
    numericCode: "332",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "HUF",
    name: "Hungarian Forint",
    nativeName: "magyar forint",
    symbol: "Ft",
    nativeSymbol: "Ft",
    numericCode: "348",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    nativeName: "Rupiah Indonesia",
    symbol: "Rp",
    nativeSymbol: "Rp",
    numericCode: "360",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "ILS",
    name: "Israeli New Shekel",
    nativeName: "שקל חדש",
    symbol: "₪",
    nativeSymbol: "₪",
    numericCode: "376",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "INR",
    name: "Indian Rupee",
    nativeName: "भारतीय रुपया",
    symbol: "₹",
    nativeSymbol: "₹",
    numericCode: "356",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    nativeName: "دينار عراقي",
    symbol: "IQD",
    nativeSymbol: "د.ع.",
    numericCode: "368",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "IRR",
    name: "Iranian Rial",
    nativeName: "ریال ایران",
    symbol: "IRR",
    nativeSymbol: "ریال",
    numericCode: "364",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "ISK",
    name: "Icelandic Króna",
    nativeName: "íslensk króna",
    symbol: "kr",
    nativeSymbol: "kr.",
    numericCode: "352",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "JMD",
    name: "Jamaican Dollar",
    nativeName: "Jamaican Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "388",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "JOD",
    name: "Jordanian Dinar",
    nativeName: "دينار أردني",
    symbol: "JOD",
    nativeSymbol: "د.أ.",
    numericCode: "400",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    nativeName: "日本円",
    symbol: "¥",
    nativeSymbol: "￥",
    numericCode: "392",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "KES",
    name: "Kenyan Shilling",
    nativeName: "Kenyan Shilling",
    symbol: "KES",
    nativeSymbol: "Ksh",
    numericCode: "404",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "KGS",
    name: "Kyrgyz Som",
    nativeName: "Кыргызстан сому",
    symbol: "⃀",
    nativeSymbol: "⃀",
    numericCode: "417",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "KHR",
    name: "Cambodian Riel",
    nativeName: "រៀល​កម្ពុជា",
    symbol: "៛",
    nativeSymbol: "៛",
    numericCode: "116",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "KMF",
    name: "Comorian Franc",
    nativeName: "فرنك جزر القمر",
    symbol: "CF",
    nativeSymbol: "CF",
    numericCode: "174",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "KPW",
    name: "North Korean Won",
    nativeName: "조선 민주주의 인민 공화국 원",
    symbol: "₩",
    nativeSymbol: "₩",
    numericCode: "408",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "KRW",
    name: "South Korean Won",
    nativeName: "대한민국 원",
    symbol: "₩",
    nativeSymbol: "₩",
    numericCode: "410",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    nativeName: "دينار كويتي",
    symbol: "KWD",
    nativeSymbol: "د.ك.",
    numericCode: "414",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "KYD",
    name: "Cayman Islands Dollar",
    nativeName: "Cayman Islands Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "136",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    nativeName: "Қазақстан теңгесі",
    symbol: "₸",
    nativeSymbol: "₸",
    numericCode: "398",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "LAK",
    name: "Laotian Kip",
    nativeName: "ລາວ ກີບ",
    symbol: "₭",
    nativeSymbol: "₭",
    numericCode: "418",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "LBP",
    name: "Lebanese Pound",
    nativeName: "جنيه لبناني",
    symbol: "L£",
    nativeSymbol: "L£",
    numericCode: "422",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    nativeName: "ශ්‍රී ලංකා රුපියල",
    symbol: "Rs",
    nativeSymbol: "රු.",
    numericCode: "144",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "LRD",
    name: "Liberian Dollar",
    nativeName: "Liberian Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "430",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "LSL",
    name: "Lesotho Loti",
    nativeName: "Lesotho Loti",
    symbol: "LSL",
    nativeSymbol: "LSL",
    numericCode: "426",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "LYD",
    name: "Libyan Dinar",
    nativeName: "دينار ليبي",
    symbol: "LYD",
    nativeSymbol: "د.ل.",
    numericCode: "434",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MAD",
    name: "Moroccan Dirham",
    nativeName: "dírham marroquí",
    symbol: "MAD",
    nativeSymbol: "MAD",
    numericCode: "504",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MDL",
    name: "Moldovan Leu",
    nativeName: "leu moldovenesc",
    symbol: "MDL",
    nativeSymbol: "L",
    numericCode: "498",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MGA",
    name: "Malagasy Ariary",
    nativeName: "ariary malgache",
    symbol: "Ar",
    nativeSymbol: "Ar",
    numericCode: "969",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MKD",
    name: "Macedonian Denar",
    nativeName: "Македонски денар",
    symbol: "MKD",
    nativeSymbol: "ден.",
    numericCode: "807",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MMK",
    name: "Myanmar Kyat",
    nativeName: "မြန်မာ ကျပ်",
    symbol: "K",
    nativeSymbol: "K",
    numericCode: "104",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MNT",
    name: "Mongolian Tugrik",
    nativeName: "Монгол төгрөг",
    symbol: "₮",
    nativeSymbol: "₮",
    numericCode: "496",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MOP",
    name: "Macanese Pataca",
    nativeName: "澳門元",
    symbol: "MOP",
    nativeSymbol: "MOP$",
    numericCode: "446",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MRU",
    name: "Mauritanian Ouguiya",
    nativeName: "أوقية موريتانية",
    symbol: "MRU",
    nativeSymbol: "أ.م.",
    numericCode: "929",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MUR",
    name: "Mauritian Rupee",
    nativeName: "Mauritian Rupee",
    symbol: "Rs",
    nativeSymbol: "Rs",
    numericCode: "480",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MVR",
    name: "Maldivian Rufiyaa",
    nativeName: "Maldivian Rufiyaa",
    symbol: "MVR",
    nativeSymbol: "ރ.",
    numericCode: "462",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MWK",
    name: "Malawian Kwacha",
    nativeName: "Malawian Kwacha",
    symbol: "MWK",
    nativeSymbol: "MK",
    numericCode: "454",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MXN",
    name: "Mexican Peso",
    nativeName: "peso mexicano",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "484",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MXV",
    name: "Mexican Investment Unit",
    nativeName: "Mexican Investment Unit",
    symbol: "MXV",
    nativeSymbol: "MXV",
    numericCode: "979",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    nativeName: "Ringgit Malaysia",
    symbol: "RM",
    nativeSymbol: "RM",
    numericCode: "458",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "MZN",
    name: "Mozambican Metical",
    nativeName: "metical moçambicano",
    symbol: "MZN",
    nativeSymbol: "MTn",
    numericCode: "943",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "NAD",
    name: "Namibian Dollar",
    nativeName: "Namibian Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "516",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "NGN",
    name: "Nigerian Naira",
    nativeName: "Nigerian Naira",
    symbol: "₦",
    nativeSymbol: "₦",
    numericCode: "566",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "NIO",
    name: "Nicaraguan Córdoba",
    nativeName: "córdoba nicaragüense",
    symbol: "C$",
    nativeSymbol: "C$",
    numericCode: "558",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    nativeName: "norske kroner",
    symbol: "kr",
    nativeSymbol: "kr",
    numericCode: "578",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "NPR",
    name: "Nepalese Rupee",
    nativeName: "नेपाली रूपैयाँ",
    symbol: "Rs",
    nativeSymbol: "रू",
    numericCode: "524",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    nativeName: "New Zealand Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "554",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "OMR",
    name: "Omani Rial",
    nativeName: "ريال عماني",
    symbol: "OMR",
    nativeSymbol: "ر.ع.",
    numericCode: "512",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "PAB",
    name: "Panamanian Balboa",
    nativeName: "balboa panameño",
    symbol: "PAB",
    nativeSymbol: "B/.",
    numericCode: "590",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "PEN",
    name: "Peruvian Sol",
    nativeName: "sol peruano",
    symbol: "PEN",
    nativeSymbol: "S/",
    numericCode: "604",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "PGK",
    name: "Papua New Guinean Kina",
    nativeName: "Papua New Guinean Kina",
    symbol: "PGK",
    nativeSymbol: "K",
    numericCode: "598",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    nativeName: "Philippine Peso",
    symbol: "₱",
    nativeSymbol: "₱",
    numericCode: "608",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "PKR",
    name: "Pakistani Rupee",
    nativeName: "Pakistani Rupee",
    symbol: "Rs",
    nativeSymbol: "Rs",
    numericCode: "586",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "PLN",
    name: "Polish Zloty",
    nativeName: "złoty polski",
    symbol: "zł",
    nativeSymbol: "zł",
    numericCode: "985",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "PYG",
    name: "Paraguayan Guarani",
    nativeName: "guaraní paraguayo",
    symbol: "₲",
    nativeSymbol: "₲",
    numericCode: "600",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "QAR",
    name: "Qatari Riyal",
    nativeName: "ريال قطري",
    symbol: "QAR",
    nativeSymbol: "ر.ق.",
    numericCode: "634",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "RON",
    name: "Romanian Leu",
    nativeName: "leu românesc",
    symbol: "lei",
    nativeSymbol: "lei",
    numericCode: "946",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "RSD",
    name: "Serbian Dinar",
    nativeName: "српски динар",
    symbol: "RSD",
    nativeSymbol: "RSD",
    numericCode: "941",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    nativeName: "российский рубль",
    symbol: "₽",
    nativeSymbol: "₽",
    numericCode: "643",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "RWF",
    name: "Rwandan Franc",
    nativeName: "Rwandan Franc",
    symbol: "RF",
    nativeSymbol: "RF",
    numericCode: "646",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    nativeName: "ريال سعودي",
    symbol: "SAR",
    nativeSymbol: "ر.س.",
    numericCode: "682",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    nativeName: "Solomon Islands Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "090",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SCR",
    name: "Seychellois Rupee",
    nativeName: "roupie des Seychelles",
    symbol: "SCR",
    nativeSymbol: "SR",
    numericCode: "690",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SDG",
    name: "Sudanese Pound",
    nativeName: "جنيه سوداني",
    symbol: "SDG",
    nativeSymbol: "ج.س.",
    numericCode: "938",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    nativeName: "svensk krona",
    symbol: "kr",
    nativeSymbol: "kr",
    numericCode: "752",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    nativeName: "Singapore Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "702",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SHP",
    name: "St. Helena Pound",
    nativeName: "St. Helena Pound",
    symbol: "£",
    nativeSymbol: "£",
    numericCode: "654",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SLE",
    name: "Sierra Leonean Leone",
    nativeName: "Sierra Leonean Leone",
    symbol: "SLE",
    nativeSymbol: "Le",
    numericCode: "925",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SLL",
    name: "Sierra Leonean Leone",
    nativeName: "Sierra Leonean Leone",
    symbol: "SLL",
    nativeSymbol: "SLL",
    numericCode: "694",
    minorUnit: 2,
    status: "historical",
    source: "ISO4217+CLDR"
  },
  {
    code: "SOS",
    name: "Somali Shilling",
    nativeName: "Shilingka Soomaaliya",
    symbol: "SOS",
    nativeSymbol: "S",
    numericCode: "706",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SRD",
    name: "Surinamese Dollar",
    nativeName: "Surinaamse dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "968",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SSP",
    name: "South Sudanese Pound",
    nativeName: "South Sudanese Pound",
    symbol: "£",
    nativeSymbol: "£",
    numericCode: "728",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "STN",
    name: "São Tomé & Príncipe Dobra",
    nativeName: "dobra de São Tomé e Príncipe",
    symbol: "Db",
    nativeSymbol: "Db",
    numericCode: "930",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SVC",
    name: "Salvadoran Colón",
    nativeName: "colón salvadoreño",
    symbol: "SVC",
    nativeSymbol: "SVC",
    numericCode: "222",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SYP",
    name: "Syrian Pound",
    nativeName: "ليرة سورية",
    symbol: "£",
    nativeSymbol: "£",
    numericCode: "760",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "SZL",
    name: "Swazi Lilangeni",
    nativeName: "Swazi Lilangeni",
    symbol: "SZL",
    nativeSymbol: "E",
    numericCode: "748",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "THB",
    name: "Thai Baht",
    nativeName: "บาท",
    symbol: "฿",
    nativeSymbol: "฿",
    numericCode: "764",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "TJS",
    name: "Tajikistani Somoni",
    nativeName: "Сомонии Тоҷикистон",
    symbol: "TJS",
    nativeSymbol: "сом.",
    numericCode: "972",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "TMT",
    name: "Turkmenistani Manat",
    nativeName: "Türkmen manady",
    symbol: "TMT",
    nativeSymbol: "TMT",
    numericCode: "934",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "TND",
    name: "Tunisian Dinar",
    nativeName: "دينار تونسي",
    symbol: "TND",
    nativeSymbol: "د.ت.",
    numericCode: "788",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "TOP",
    name: "Tongan Paʻanga",
    nativeName: "Tongan Paʻanga",
    symbol: "T$",
    nativeSymbol: "T$",
    numericCode: "776",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    nativeName: "Türk lirası",
    symbol: "₺",
    nativeSymbol: "₺",
    numericCode: "949",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "TTD",
    name: "Trinidad & Tobago Dollar",
    nativeName: "Trinidad & Tobago Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "780",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "TWD",
    name: "New Taiwan Dollar",
    nativeName: "新台幣",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "901",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    nativeName: "Shilingi ya Tanzania",
    symbol: "TZS",
    nativeSymbol: "TSh",
    numericCode: "834",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "UAH",
    name: "Ukrainian Hryvnia",
    nativeName: "українська гривня",
    symbol: "₴",
    nativeSymbol: "₴",
    numericCode: "980",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "UGX",
    name: "Ugandan Shilling",
    nativeName: "Ugandan Shilling",
    symbol: "UGX",
    nativeSymbol: "USh",
    numericCode: "800",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "USD",
    name: "US Dollar",
    nativeName: "US Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "840",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "USN",
    name: "US Dollar (Next day)",
    nativeName: "US Dollar (Next day)",
    symbol: "USN",
    nativeSymbol: "USN",
    numericCode: "997",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "USS",
    name: "US Dollar (Same day)",
    nativeName: "US Dollar (Same day)",
    symbol: "USS",
    nativeSymbol: "USS",
    numericCode: "998",
    minorUnit: 2,
    status: "historical",
    source: "ISO4217+CLDR"
  },
  {
    code: "UYI",
    name: "Uruguayan Peso (Indexed Units)",
    nativeName: "peso uruguayo en unidades indexadas",
    symbol: "UYI",
    nativeSymbol: "UYI",
    numericCode: "940",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "UYU",
    name: "Uruguayan Peso",
    nativeName: "peso uruguayo",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "858",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "UYW",
    name: "Uruguayan Nominal Wage Index Unit",
    nativeName: "Uruguayan Nominal Wage Index Unit",
    symbol: "UYW",
    nativeSymbol: "UYW",
    numericCode: "927",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "UZS",
    name: "Uzbekistani Som",
    nativeName: "O‘zbekiston so‘mi",
    symbol: "UZS",
    nativeSymbol: "soʻm",
    numericCode: "860",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "VED",
    name: "Bolívar Soberano",
    nativeName: "Bolívar Soberano",
    symbol: "VED",
    nativeSymbol: "VED",
    numericCode: "926",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "VES",
    name: "Venezuelan Bolívar",
    nativeName: "bolívar soberano",
    symbol: "VES",
    nativeSymbol: "Bs.S",
    numericCode: "928",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "VND",
    name: "Vietnamese Dong",
    nativeName: "Đồng Việt Nam",
    symbol: "₫",
    nativeSymbol: "₫",
    numericCode: "704",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "VUV",
    name: "Vanuatu Vatu",
    nativeName: "Vanuatu Vatu",
    symbol: "VUV",
    nativeSymbol: "VUV",
    numericCode: "548",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "WST",
    name: "Samoan Tala",
    nativeName: "Samoan Tala",
    symbol: "WST",
    nativeSymbol: "WST",
    numericCode: "882",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XAD",
    name: "Arab Accounting Dinar",
    nativeName: "Arab Accounting Dinar",
    symbol: "XAD",
    nativeSymbol: "XAD",
    numericCode: "396",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XAF",
    name: "Central African CFA Franc",
    nativeName: "franc CFA (BEAC)",
    symbol: "FCFA",
    nativeSymbol: "FCFA",
    numericCode: "950",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XAG",
    name: "Silver",
    nativeName: "Silver",
    symbol: "XAG",
    nativeSymbol: "XAG",
    numericCode: "961",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XAU",
    name: "Gold",
    nativeName: "Gold",
    symbol: "XAU",
    nativeSymbol: "XAU",
    numericCode: "959",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XBA",
    name: "European Composite Unit",
    nativeName: "European Composite Unit",
    symbol: "XBA",
    nativeSymbol: "XBA",
    numericCode: "955",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XBB",
    name: "European Monetary Unit",
    nativeName: "European Monetary Unit",
    symbol: "XBB",
    nativeSymbol: "XBB",
    numericCode: "956",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XBC",
    name: "European Unit of Account (XBC)",
    nativeName: "European Unit of Account (XBC)",
    symbol: "XBC",
    nativeSymbol: "XBC",
    numericCode: "957",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XBD",
    name: "European Unit of Account (XBD)",
    nativeName: "European Unit of Account (XBD)",
    symbol: "XBD",
    nativeSymbol: "XBD",
    numericCode: "958",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XCD",
    name: "East Caribbean Dollar",
    nativeName: "East Caribbean Dollar",
    symbol: "$",
    nativeSymbol: "$",
    numericCode: "951",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XCG",
    name: "Caribbean guilder",
    nativeName: "Caribische gulden",
    symbol: "Cg",
    nativeSymbol: "Cg",
    numericCode: "532",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XDR",
    name: "Special Drawing Rights",
    nativeName: "Special Drawing Rights",
    symbol: "XDR",
    nativeSymbol: "XDR",
    numericCode: "960",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XOF",
    name: "West African CFA Franc",
    nativeName: "franc CFA (BCEAO)",
    symbol: "F CFA",
    nativeSymbol: "F CFA",
    numericCode: "952",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XPD",
    name: "Palladium",
    nativeName: "Palladium",
    symbol: "XPD",
    nativeSymbol: "XPD",
    numericCode: "964",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XPF",
    name: "CFP Franc",
    nativeName: "franc CFP",
    symbol: "CFPF",
    nativeSymbol: "FCFP",
    numericCode: "953",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XPT",
    name: "Platinum",
    nativeName: "Platinum",
    symbol: "XPT",
    nativeSymbol: "XPT",
    numericCode: "962",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XSU",
    name: "Sucre",
    nativeName: "Sucre",
    symbol: "XSU",
    nativeSymbol: "XSU",
    numericCode: "994",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XTS",
    name: "Testing Currency Code",
    nativeName: "Testing Currency Code",
    symbol: "XTS",
    nativeSymbol: "XTS",
    numericCode: "963",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XUA",
    name: "ADB Unit of Account",
    nativeName: "ADB Unit of Account",
    symbol: "XUA",
    nativeSymbol: "XUA",
    numericCode: "965",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "XXX",
    name: "Unknown Currency",
    nativeName: "Unknown Currency",
    symbol: "¤",
    nativeSymbol: "¤",
    numericCode: "999",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "YER",
    name: "Yemeni Rial",
    nativeName: "ريال يمني",
    symbol: "YER",
    nativeSymbol: "ر.ي.",
    numericCode: "886",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "ZAR",
    name: "South African Rand",
    nativeName: "Suid-Afrikaanse rand",
    symbol: "R",
    nativeSymbol: "R",
    numericCode: "710",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "ZMW",
    name: "Zambian Kwacha",
    nativeName: "Zambian Kwacha",
    symbol: "ZK",
    nativeSymbol: "ZK",
    numericCode: "967",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  },
  {
    code: "ZWG",
    name: "Zimbabwean Gold",
    nativeName: "Zimbabwean Gold",
    symbol: "ZWG",
    nativeSymbol: "ZWG",
    numericCode: "924",
    minorUnit: 2,
    status: "active",
    source: "ISO4217+CLDR"
  }
];
const byCode = new Map(CURRENCY_REGISTRY.map(currency => [currency.code, currency]));
export function getCurrency(code:string|null|undefined){ return code ? byCode.get(code.toUpperCase()) : undefined; }
export function getCurrencyName(code:string, locale="en"){ const c=getCurrency(code); if(!c)return code.toUpperCase(); try { return new Intl.DisplayNames([locale],{type:"currency"}).of(c.code)||c.name; } catch { return c.name; } }
export function searchCurrencies(query:string, options?:{includeHistorical?:boolean}){ const q=query.trim().toLowerCase(); const historical=options?.includeHistorical??true; return CURRENCY_REGISTRY.filter(c=>{if(!historical&&c.status!=="active")return false;if(!q)return true;const localized=getCurrencyName(c.code).toLowerCase();return [c.code,c.name,c.nativeName,c.numericCode,c.symbol,localized].filter(Boolean).some(v=>String(v).toLowerCase().includes(q));}); }
export const ACTIVE_CURRENCIES=CURRENCY_REGISTRY.filter(c=>c.status==="active");
export const HISTORICAL_CURRENCIES=CURRENCY_REGISTRY.filter(c=>c.status==="historical");
