import React, { useState } from 'react';
import { LayoutDashboard, Bot, FileText, Users, Building, MessageSquare, Calendar, GitPullRequest, CreditCard, Plug, Shield, Search, Bell, ChevronDown, Menu, X, CheckCircle2, AlertCircle , PanelLeft, Target, Megaphone, FolderOpen, Activity, Workflow, Settings2 } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { NavItemKey } from '../../types';
import { APEXReveal, NavigationMenu, Sidebar } from '../apex3x';
import { WorkspaceBrand } from '../workspace/WorkspaceBrand';
import { CommandPalette } from './CommandPalette';
import { ConnectDrawer } from './ConnectDrawer';
import { NotificationDrawer } from './NotificationDrawer';
import { OnboardingModal } from './OnboardingModal';
import { SubWorkspaceModal } from './SubWorkspaceModal';
import { useSidebarInteraction } from './useSidebarInteraction';

interface NavSection { title: string; items: { key: NavItemKey; label: string; icon: React.ReactNode; badge?: string }[]; }

export const AppShell: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { organisation, currentWorkspace, availableWorkspaces, currentUser, activeNav, setActiveNav, switchWorkspace, setCommandPaletteOpen, setNotificationDrawerOpen, setOnboardingOpen, setSubWorkspaceOpen, toasts, removeToast } = useApp();
  const [workspaceMenuOpen, setWorkspaceMenuOpen] = useState(false);
  const { collapsed, mobileOpen, dragX, drawerRef, mobileTriggerRef, toggleCollapsed, openMobile, closeMobile, handlePointerDown, handlePointerMove, handlePointerUp, handlePointerCancel, edgeWidth } = useSidebarInteraction();
  const navSections: NavSection[] = [
    { title: 'Core', items: [{ key: 'dashboard', label: 'Command Center', icon: <LayoutDashboard className="w-4 h-4" /> }, { key: 'conversations', label: 'Unified Inbox', icon: <MessageSquare className="w-4 h-4" /> }] },
    { title: 'Attract & Capture', items: [{ key: 'campaigns', label: 'Campaigns', icon: <Target className="w-4 h-4" /> }, { key: 'advertising', label: 'Advertising', icon: <Megaphone className="w-4 h-4" /> }, { key: 'creative_library', label: 'Creative Library', icon: <FolderOpen className="w-4 h-4" /> }, { key: 'social_publishing', label: 'Social Publishing', icon: <MessageSquare className="w-4 h-4" /> }, { key: 'forms', label: 'Forms & Web Capture', icon: <FileText className="w-4 h-4" /> }, { key: 'growth_intelligence', label: 'Growth Intelligence', icon: <Activity className="w-4 h-4" /> }] },
    { title: 'Qualify & Convert', items: [{ key: 'leads', label: 'Leads', icon: <Users className="w-4 h-4" /> }, { key: 'customers', label: 'Customers', icon: <Building className="w-4 h-4" /> }] },
    { title: 'Book & Schedule', items: [{ key: 'bookings', label: 'Bookings & Calendar', icon: <Calendar className="w-4 h-4" /> }] },
    { title: 'Sell & Revenue', items: [{ key: 'pipeline', label: 'Sales Pipeline', icon: <GitPullRequest className="w-4 h-4" /> }, { key: 'invoices', label: 'Invoices & Payments', icon: <CreditCard className="w-4 h-4" /> }] },
    { title: 'Automation', items: [{ key: 'workflows', label: 'Automate', icon: <Workflow className="w-4 h-4" /> }] },
    { title: 'Connected Ecosystem', items: [{ key: 'integrations', label: 'Integrations Hub', icon: <Plug className="w-4 h-4" /> }, { key: 'ai_hub', label: 'AI Provider Hub', icon: <Bot className="w-4 h-4" /> }] },
    { title: 'Governance', items: [{ key: 'team', label: 'Team & Security', icon: <Shield className="w-4 h-4" /> }, { key: 'billing', label: 'Billing & Entitlements', icon: <CreditCard className="w-4 h-4" /> }, { key: 'settings', label: 'Workspace Settings', icon: <Settings2 className="w-4 h-4" /> }] },
  ];
  const userName = currentUser?.name || 'Account unavailable';
  const selectNav = (key: string) => setActiveNav(key as NavItemKey);
  const drawerTransform = dragX !== null ? `translateX(${dragX}px)` : mobileOpen ? 'translateX(0)' : 'translateX(-100%)';
  const drawerTransition = dragX === null ? 'transform 280ms cubic-bezier(0.4, 0, 0.2, 1)' : 'none';

  return <div className="h-screen min-h-0 overflow-hidden bg-[var(--background)] text-[var(--text-primary)] flex flex-col antialiased selection:bg-white/15 selection:text-white">
    <a href="#apex-main-content" className="sr-only focus:not-sr-only focus:fixed focus:left-3 focus:top-3 focus:z-[100] focus:rounded-md focus:bg-[var(--bg-brand)] focus:px-3 focus:py-2 focus:text-sm focus:font-semibold focus:text-[var(--text-on-brand)]">Skip to main content</a>\n    <header role="banner" className="h-14 shrink-0 border-b border-[var(--border)] bg-[var(--background)] flex items-center justify-between px-3 sm:px-5 lg:px-6 z-40">
      <div className="flex min-w-0 items-center">
        <button ref={mobileTriggerRef} onClick={() => mobileOpen ? closeMobile() : openMobile()} className="lg:hidden inline-flex h-8 w-8 items-center justify-center rounded-[var(--radius-sm)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--surface)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)]" aria-label={mobileOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={mobileOpen} title={mobileOpen ? 'Close navigation' : 'Open navigation'}>{mobileOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}</button>
        <div className="relative min-w-0">
          <button onClick={() => setWorkspaceMenuOpen(v => !v)} className="flex items-center gap-2 rounded-[var(--radius-sm)] px-1.5 py-1.5 hover:bg-[var(--surface)] text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)]" aria-label="Open organisation and workspace menu" aria-expanded={workspaceMenuOpen} title="Organisation and workspace">
            <div className="flex items-center gap-2 shrink-0">
              <div className="w-7 h-7 rounded-[var(--radius-sm)] bg-[var(--text-primary)] flex items-center justify-center overflow-hidden text-[var(--background)] font-semibold text-sm">{organisation.logoUrl ? <img src={organisation.logoUrl} alt={`${organisation.name} logo`} className="h-full w-full object-cover" /> : organisation.shortName.trim().charAt(0).toUpperCase() || '—'}</div>
              <span className="font-brand font-semibold text-xs tracking-wider text-[var(--text-primary)]">{organisation.shortName || organisation.name}</span>
              <span className="text-[9px] px-1 py-0.5 rounded-[var(--radius-sm)] bg-[var(--surface)] text-[var(--text-secondary)] border border-[var(--border)] font-mono font-semibold">OS</span>
            </div>
            <ChevronDown className="w-3.5 h-3.5 shrink-0 text-[var(--text-muted)]" />
          </button>
          {workspaceMenuOpen && <div className="absolute left-0 top-full mt-1.5 w-64 p-1.5 bg-[var(--surface-elevated)] border border-[var(--border)] rounded-[var(--radius-sm)] shadow-[0_16px_32px_-20px_rgba(0,0,0,0.95)] z-50"><div className="px-2 py-1 text-[10px] font-medium text-[var(--text-muted)]">Workspaces</div>{availableWorkspaces.length === 0 ? <div className="px-2 py-2 text-[11px] text-[var(--text-muted)]">No workspaces available.</div> : availableWorkspaces.map(ws => <button key={ws.id} onClick={() => { switchWorkspace(ws.id); setWorkspaceMenuOpen(false); }} className={`w-full flex items-center justify-between px-2.5 py-1.5 rounded-[var(--radius-sm)] text-xs text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)] ${ws.id === currentWorkspace?.id ? 'bg-[var(--surface-2)] text-[var(--text-primary)] font-semibold' : 'text-[var(--text-secondary)] hover:bg-[var(--surface-2)]'}`}><WorkspaceBrand workspace={ws} organisation={organisation} compact />{ws.id === currentWorkspace?.id && <CheckCircle2 className="w-3 h-3 text-[var(--text-primary)] shrink-0" />}</button>)}<div className="pt-1 mt-1 border-t border-[var(--border)]"><button onClick={() => { setWorkspaceMenuOpen(false); setSubWorkspaceOpen(true); }} className="w-full px-2.5 py-1.5 rounded-[var(--radius-sm)] text-xs text-[var(--text-secondary)] hover:bg-[var(--surface-2)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)] text-left">Sub workspace</button></div></div>}
        </div>
      </div>
      <div className="flex items-center gap-2 sm:gap-3 shrink-0"><div className="hidden lg:block"><NavigationMenu sections={navSections} activeKey={activeNav} onSelect={selectNav} /></div><button onClick={() => setCommandPaletteOpen(true)} className="inline-flex h-8 w-8 items-center justify-center rounded-[var(--radius-sm)] bg-[var(--surface)] border border-[var(--border)] hover:border-[var(--border-strong)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)]" aria-label="Open search" title="Search"><Search className="w-3.5 h-3.5" /></button><button onClick={() => setNotificationDrawerOpen(true)} className="relative p-2 rounded-[var(--radius-sm)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--surface)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)]" title="Decision feed" aria-label="Open decision feed"><Bell className="w-4 h-4" /></button><button onClick={() => setOnboardingOpen(true)} className="hidden md:inline-flex items-center gap-1.5 px-2.5 py-1 rounded-[var(--radius-sm)] text-[11px] font-medium border bg-[var(--surface)] text-[var(--text-secondary)] border-[var(--border)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)]"><Building className="w-3 h-3" /><span>Business profile</span></button></div>
    </header> <div className="min-h-0 flex-1 flex overflow-hidden">
      <aside role="navigation" aria-label="Primary navigation" className={`${collapsed ? 'w-16' : 'w-[280px]'} hidden lg:flex min-h-0 flex-col bg-[var(--sidebar)] border-r border-[var(--border)] shrink-0 select-none overflow-hidden transition-[width] duration-200 ease-[cubic-bezier(0.4,0,0.2,1)]`} role="navigation" aria-label="Primary navigation">
        <div className={`h-12 shrink-0 border-b border-[var(--border)] flex items-center ${collapsed ? 'justify-center px-2' : 'justify-between px-3'}`}>{!collapsed && <p className="text-[10px] font-medium text-[var(--text-muted)]">Navigation</p>}<button type="button" onClick={toggleCollapsed} className="inline-flex h-8 w-8 items-center justify-center rounded-[var(--radius-sm)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--surface)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)]" aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'} aria-expanded={!collapsed} title={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}><PanelLeft className="w-4 h-4" /></button></div>
        <Sidebar sections={navSections} activeKey={activeNav} onSelect={selectNav} collapsed={collapsed} />
        <div className={`shrink-0 border-t border-[var(--border)] bg-[var(--sidebar)] ${collapsed ? 'p-2 flex justify-center' : 'p-3'}`}><button type="button" className={`flex items-center ${collapsed ? 'justify-center h-9 w-9' : 'w-full'} gap-2 rounded-[var(--radius-sm)] text-left hover:bg-[var(--surface)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)]`} aria-label="Open account menu" title={collapsed ? userName : undefined}><div className="w-7 h-7 rounded-full bg-[var(--surface)] text-[var(--text-primary)] border border-[var(--border)] flex items-center justify-center text-[10px] font-semibold shrink-0">{currentUser?.name ? currentUser.name.charAt(0) : '—'}</div>{!collapsed && <div className="truncate"><p className="text-[11px] font-medium text-[var(--text-secondary)] truncate">{userName}</p>{currentUser?.role && <p className="text-[9px] text-[var(--text-muted)] capitalize">{currentUser.role}</p>}</div>}</button></div>
      </aside>
      <main id="apex-main-content" tabIndex={-1} className="min-h-0 min-w-0 flex-1 overflow-y-auto overflow-x-hidden overscroll-contain bg-[var(--background)] p-4 sm:p-6 lg:p-8"><div className="max-w-7xl mx-auto w-full apex-scroll-reveal"><APEXReveal>{children}</APEXReveal></div></main>
    </div>
    <div className={`fixed inset-0 z-[60] lg:hidden ${mobileOpen || dragX !== null ? 'pointer-events-auto' : 'pointer-events-none'}`} aria-hidden={!mobileOpen && dragX === null}>
      <div className={`absolute inset-0 bg-black/80 transition-opacity duration-280 ${mobileOpen ? 'opacity-100' : 'opacity-0'}`} onClick={() => closeMobile()} />
      <aside ref={drawerRef} className="absolute left-0 top-0 bottom-0 w-[min(19rem,88vw)] bg-[var(--sidebar)] border-r border-[var(--border)] flex flex-col overflow-hidden shadow-[16px_0_48px_-32px_rgba(0,0,0,0.95)] touch-pan-y" style={{ transform: drawerTransform, transition: drawerTransition }} onPointerDown={event => handlePointerDown(event, 'close-drawer')} onPointerMove={handlePointerMove} onPointerUp={handlePointerUp} onPointerCancel={handlePointerCancel}>
        <div className="h-14 shrink-0 flex items-center justify-between px-4 border-b border-[var(--border)]"><div className="flex min-w-0 items-center gap-2.5"><div className="h-7 w-7 rounded-lg bg-[var(--text-primary)] flex items-center justify-center overflow-hidden text-[var(--background)] text-[10px] font-bold">{organisation.logoUrl ? <img src={organisation.logoUrl} alt={`${organisation.name} logo`} className="h-full w-full object-cover" /> : organisation.shortName.trim().charAt(0).toUpperCase() || '—'}</div><span className="min-w-0 truncate text-xs font-semibold text-[var(--text-primary)]">{organisation.shortName || organisation.name}</span></div><button type="button" onClick={() => closeMobile()} className="inline-flex h-8 w-8 items-center justify-center rounded-[var(--radius-sm)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--surface)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)]" aria-label="Close navigation" title="Close navigation"><X className="w-5 h-5" /></button></div>
        <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain"><Sidebar sections={navSections} activeKey={activeNav} onSelect={selectNav} onMobileSelect={() => closeMobile()} mobile /></div>
        <div className="shrink-0 border-t border-[var(--border)] p-3"><div className="flex items-center gap-2"><div className="w-7 h-7 rounded-full bg-[var(--surface)] text-[var(--text-primary)] border border-[var(--border)] flex items-center justify-center text-[10px] font-semibold">{currentUser?.name ? currentUser.name.charAt(0) : '—'}</div><div className="truncate"><p className="text-[11px] font-medium text-[var(--text-secondary)] truncate">{userName}</p>{currentUser?.role && <p className="text-[9px] text-[var(--text-muted)] capitalize">{currentUser.role}</p>}</div></div></div>
      </aside>
    </div>
    {!mobileOpen && <div className="fixed left-0 top-14 bottom-0 z-[55] lg:hidden touch-pan-y" style={{ width: edgeWidth }} onPointerDown={event => handlePointerDown(event, 'open-edge')} onPointerMove={handlePointerMove} onPointerUp={handlePointerUp} onPointerCancel={handlePointerCancel} aria-hidden="true" />}
    <CommandPalette /><ConnectDrawer /><NotificationDrawer /><OnboardingModal /><SubWorkspaceModal />
    <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2 pointer-events-none max-w-sm w-full">{toasts.map(toast => <div key={toast.id} className="pointer-events-auto p-3.5 rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface-elevated)] shadow-[0_12px_28px_-20px_rgba(0,0,0,0.95)] flex items-start gap-3"><div className="shrink-0 mt-0.5">{toast.type === 'success' && <CheckCircle2 className="w-4 h-4 text-[var(--success)]" />}{toast.type === 'warning' && <AlertCircle className="w-4 h-4 text-[var(--warning)]" />}{toast.type === 'error' && <AlertCircle className="w-4 h-4 text-[var(--error)]" />}{toast.type === 'info' && <Bot className="w-4 h-4 text-[var(--info)]" />}</div><div className="flex-1 min-w-0"><p className="text-xs font-semibold">{toast.title}</p>{toast.description && <p className="text-[11px] text-[var(--text-secondary)] mt-0.5 leading-snug">{toast.description}</p>}</div><button onClick={() => removeToast(toast.id)} className="text-[var(--text-muted)] p-0.5 shrink-0 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)]" aria-label="Dismiss notification"><X className="w-3 h-3" /></button></div>)}</div>
  </div>;
};