import React, { useState } from 'react';
import { LayoutDashboard, Bot, FileText, TrendingUp, Users, Building, MessageSquare, Calendar, GitPullRequest, CreditCard, Zap, Plug, Sparkles, Shield, Search, Bell, ChevronDown, Menu, X, CheckCircle2, AlertCircle, Command } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { NavItemKey } from '../../types';
import { APEXReveal, NavigationMenu, Sidebar } from '../apex3x';
import { WorkspaceBrand } from '../workspace/WorkspaceBrand';
import { CommandPalette } from './CommandPalette';
import { ConnectDrawer } from './ConnectDrawer';
import { NotificationDrawer } from './NotificationDrawer';
import { OnboardingModal } from './OnboardingModal';
import { SubWorkspaceModal } from './SubWorkspaceModal';

interface NavSection { title: string; items: { key: NavItemKey; label: string; icon: React.ReactNode; badge?: string }[]; }

export const AppShell: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { currentWorkspace, availableWorkspaces, currentUser, activeNav, setActiveNav, switchWorkspace, setCommandPaletteOpen, setNotificationDrawerOpen, setOnboardingOpen, setSubWorkspaceOpen, toasts, removeToast } = useApp();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [workspaceMenuOpen, setWorkspaceMenuOpen] = useState(false);
  const navSections: NavSection[] = [
    { title: 'Operational command', items: [{ key: 'dashboard', label: 'Command Center', icon: <LayoutDashboard className="w-4 h-4" /> }, { key: 'brain', label: 'Autonomous Brain', icon: <Bot className="w-4 h-4" /> }, { key: 'insights', label: 'Business Insights', icon: <Sparkles className="w-4 h-4" /> }] },
    { title: 'Attract and capture', items: [{ key: 'forms', label: 'Forms and Web Capture', icon: <FileText className="w-4 h-4" /> }, { key: 'marketing', label: 'Growth and Ad Intelligence', icon: <TrendingUp className="w-4 h-4" /> }] },
    { title: 'Qualify and convert', items: [{ key: 'leads', label: 'CRM and Qualified Leads', icon: <Users className="w-4 h-4" /> }, { key: 'customers', label: 'Customer Directory', icon: <Building className="w-4 h-4" /> }] },
    { title: 'Communicate', items: [{ key: 'conversations', label: 'Unified Inbox', icon: <MessageSquare className="w-4 h-4" /> }] },
    { title: 'Book and schedule', items: [{ key: 'bookings', label: 'Bookings and Calendar', icon: <Calendar className="w-4 h-4" /> }] },
    { title: 'Sell and revenue', items: [{ key: 'pipeline', label: 'Sales Pipeline', icon: <GitPullRequest className="w-4 h-4" /> }, { key: 'invoices', label: 'Invoices and Payments', icon: <CreditCard className="w-4 h-4" /> }] },
    { title: 'Automate', items: [{ key: 'workflows', label: 'Workflows and Rules', icon: <Zap className="w-4 h-4" /> }] },
    { title: 'Connected ecosystem', items: [{ key: 'integrations', label: 'Integrations Hub', icon: <Plug className="w-4 h-4" /> }, { key: 'ai_hub', label: 'AI Provider Hub (BYOK)', icon: <Sparkles className="w-4 h-4" /> }] },
    { title: 'Governance', items: [{ key: 'team_security', label: 'Team and Security Audit', icon: <Shield className="w-4 h-4" /> }, { key: 'billing', label: 'Billing and Entitlements', icon: <CreditCard className="w-4 h-4" /> }] },
  ];
  const userName = currentUser?.name || 'Account unavailable';
  const selectNav = (key: string) => setActiveNav(key as NavItemKey);

  return <div className="h-screen min-h-0 overflow-hidden bg-[var(--background)] text-[var(--text-primary)] flex flex-col antialiased selection:bg-white/15 selection:text-white">
    <header className="h-14 shrink-0 border-b border-[var(--border)] bg-[var(--background)] flex items-center justify-between px-3 sm:px-5 lg:px-6 z-40">
      <div className="flex min-w-0 items-center gap-3">
        <button onClick={() => setMobileMenuOpen(v => !v)} className="lg:hidden p-1.5 rounded-[var(--radius-sm)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--surface)]" aria-label={mobileMenuOpen ? 'Close navigation' : 'Open navigation'}>{mobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}</button>
        <div className="flex items-center gap-2 shrink-0"><div className="w-7 h-7 rounded-[var(--radius-sm)] bg-[var(--text-primary)] flex items-center justify-center text-[var(--background)] font-semibold text-sm">A</div><span className="font-brand font-semibold text-xs tracking-wider text-[var(--text-primary)]">APEX3X</span><span className="text-[9px] px-1 py-0.5 rounded-[var(--radius-sm)] bg-[var(--surface)] text-[var(--text-secondary)] border border-[var(--border)] font-mono font-semibold">OS</span></div>
        <div className="hidden sm:block h-5 w-px bg-[var(--border)]" />
        <div className="relative min-w-0">
          <button onClick={() => setWorkspaceMenuOpen(v => !v)} className="flex max-w-[240px] items-center gap-2 rounded-[var(--radius-sm)] px-2 py-1.5 hover:bg-[var(--surface)] text-left" aria-label="Select workspace"><WorkspaceBrand workspace={currentWorkspace} compact /><ChevronDown className="w-3.5 h-3.5 shrink-0 text-[var(--text-muted)]" /></button>
          {workspaceMenuOpen && <div className="absolute left-0 top-full mt-1.5 w-64 p-1.5 bg-[var(--surface-elevated)] border border-[var(--border)] rounded-[var(--radius-sm)] shadow-[0_16px_32px_-20px_rgba(0,0,0,0.95)] z-50"><div className="px-2 py-1 text-[10px] font-medium text-[var(--text-muted)]">Workspaces</div>{availableWorkspaces.length === 0 ? <div className="px-2 py-2 text-[11px] text-[var(--text-muted)]">No workspaces available.</div> : availableWorkspaces.map(ws => <button key={ws.id} onClick={() => { switchWorkspace(ws.id); setWorkspaceMenuOpen(false); }} className={`w-full flex items-center justify-between px-2.5 py-1.5 rounded-[var(--radius-sm)] text-xs text-left ${ws.id === currentWorkspace?.id ? 'bg-[var(--surface-2)] text-[var(--text-primary)] font-semibold' : 'text-[var(--text-secondary)] hover:bg-[var(--surface-2)]'}`}><WorkspaceBrand workspace={ws} compact />{ws.id === currentWorkspace?.id && <CheckCircle2 className="w-3 h-3 text-[var(--text-primary)] shrink-0" />}</button>)}<div className="pt-1 mt-1 border-t border-[var(--border)]"><button onClick={() => { setWorkspaceMenuOpen(false); setSubWorkspaceOpen(true); }} className="w-full px-2.5 py-1.5 rounded-[var(--radius-sm)] text-xs text-[var(--text-secondary)] hover:bg-[var(--surface-2)] text-left">Sub workspace</button></div></div>}
        </div>
      </div>
      <div className="flex items-center gap-2 sm:gap-3 shrink-0"><div className="hidden lg:block"><NavigationMenu sections={navSections} activeKey={activeNav} onSelect={selectNav} /></div><button onClick={() => setCommandPaletteOpen(true)} className="flex items-center gap-2 px-3 py-1.5 rounded-[var(--radius-sm)] bg-[var(--surface)] border border-[var(--border)] hover:border-[var(--border-strong)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] text-xs transition-colors cursor-pointer"><Search className="w-3.5 h-3.5 text-[var(--text-muted)]" /><span className="hidden sm:inline">Search commands...</span><kbd className="hidden sm:inline-flex items-center gap-0.5 px-1.5 py-0.5 text-[10px] font-mono text-[var(--text-secondary)] bg-[var(--surface-elevated)] border border-[var(--border)] rounded-[var(--radius-sm)]"><Command className="w-2.5 h-2.5" /> K</kbd></button><button onClick={() => setNotificationDrawerOpen(true)} className="relative p-2 rounded-[var(--radius-sm)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--surface)]" title="Decision feed" aria-label="Open decision feed"><Bell className="w-4 h-4" /></button><button onClick={() => setOnboardingOpen(true)} className="hidden md:inline-flex items-center gap-1.5 px-2.5 py-1 rounded-[var(--radius-sm)] text-[11px] font-medium border bg-[var(--surface)] text-[var(--text-secondary)] border-[var(--border)]"><Building className="w-3 h-3" /><span>Business profile</span></button></div>
    </header>

    <div className="min-h-0 flex-1 flex overflow-hidden">
      <aside className="hidden lg:flex w-64 min-h-0 flex-col bg-[var(--sidebar)] border-r border-[var(--border)] shrink-0 select-none overflow-hidden"><div className="px-3 py-2.5 border-b border-[var(--border)] shrink-0"><p className="text-[10px] font-medium text-[var(--text-muted)]">Navigation</p></div><Sidebar sections={navSections} activeKey={activeNav} onSelect={selectNav} /><div className="p-3 border-t border-[var(--border)] bg-[var(--sidebar)] flex items-center text-xs shrink-0"><div className="flex items-center gap-2 min-w-0"><div className="w-6 h-6 rounded-full bg-[var(--surface)] text-[var(--text-primary)] border border-[var(--border)] flex items-center justify-center text-[10px] font-semibold shrink-0">{currentUser?.name ? currentUser.name.charAt(0) : '—'}</div><div className="truncate"><p className="text-[11px] font-medium text-[var(--text-secondary)] truncate">{userName}</p>{currentUser?.role && <p className="text-[9px] text-[var(--text-muted)] capitalize">{currentUser.role}</p>}</div></div></div></aside>
      <main className="min-h-0 min-w-0 flex-1 overflow-y-auto overflow-x-hidden overscroll-contain bg-[var(--background)] p-4 sm:p-6 lg:p-8"><div className="max-w-7xl mx-auto w-full"><APEXReveal>{children}</APEXReveal></div></main>
    </div>

    {mobileMenuOpen && <div className="fixed inset-0 z-50 lg:hidden flex"><div className="absolute inset-0 bg-black/80" onClick={() => setMobileMenuOpen(false)} /><div className="relative w-[min(19rem,88vw)] h-full min-h-0 bg-[var(--sidebar)] border-r border-[var(--border)] flex flex-col p-4 z-10 overflow-hidden"><div className="flex items-center justify-between pb-4 border-b border-[var(--border)] mb-4 shrink-0"><WorkspaceBrand workspace={currentWorkspace} compact /><button onClick={() => setMobileMenuOpen(false)} className="text-[var(--text-secondary)]" aria-label="Close navigation"><X className="w-5 h-5" /></button></div><div className="min-h-0 flex-1 overflow-y-auto overscroll-contain"><Sidebar sections={navSections} activeKey={activeNav} onSelect={selectNav} onMobileSelect={() => setMobileMenuOpen(false)} mobile /></div></div></div>}
    <CommandPalette /><ConnectDrawer /><NotificationDrawer /><OnboardingModal /><SubWorkspaceModal />
    <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2 pointer-events-none max-w-sm w-full">{toasts.map(toast => <div key={toast.id} className="pointer-events-auto p-3.5 rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface-elevated)] shadow-[0_12px_28px_-20px_rgba(0,0,0,0.95)] flex items-start gap-3"><div className="shrink-0 mt-0.5">{toast.type === 'success' && <CheckCircle2 className="w-4 h-4 text-[var(--success)]" />}{toast.type === 'warning' && <AlertCircle className="w-4 h-4 text-[var(--warning)]" />}{toast.type === 'error' && <AlertCircle className="w-4 h-4 text-[var(--error)]" />}{toast.type === 'info' && <Bot className="w-4 h-4 text-[var(--info)]" />}</div><div className="flex-1 min-w-0"><p className="text-xs font-semibold">{toast.title}</p>{toast.description && <p className="text-[11px] text-[var(--text-secondary)] mt-0.5 leading-snug">{toast.description}</p>}</div><button onClick={() => removeToast(toast.id)} className="text-[var(--text-muted)] p-0.5 shrink-0" aria-label="Dismiss notification"><X className="w-3 h-3" /></button></div>)}</div>
  </div>;
};
