import React, { useState, useEffect } from 'react';
import { useApp } from '../context/AppContext';
import { api } from '../api/client';
import { BillingEntitlement } from '../types';
import { Card, Badge, Skeleton, AnimatedNumber, AnimatedProgress, AnimatedGrid, APEXReveal } from '../components/apex3x';

export const BillingView: React.FC = () => {
  const { refreshKey } = useApp();
  const [billing, setBilling] = useState<BillingEntitlement | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { (async () => { try { setLoading(true); setBilling(await api.getBilling()); } catch (err) { console.error('Failed fetching billing info:', err); } finally { setLoading(false); } })(); }, [refreshKey]);
  if (loading || !billing) return <div className="space-y-6"><Skeleton className="h-44" /><Skeleton className="h-64" /></div>;
  const { limits } = billing; const meter = (used: number, total: number) => total ? Math.min(100, Math.round((used / total) * 100)) : 0; const meters = [['Monthly Inbound Leads', limits.leadsMonthly], ['AI Autonomous Audits & Diagnostics', limits.aiRuns], ['Active Autonomous Workflow Rules', limits.automations], ['Connected Capability Integrations', limits.connectedIntegrations]] as const;
  return <div className="space-y-6 pb-12"><APEXReveal>
    <div><div className="flex items-center gap-2"><h2 className="text-lg font-bold text-zinc-100">Subscription & Entitlements</h2><Badge variant="neutral" size="sm">{billing.planTier.toUpperCase()} TIER</Badge></div><p className="text-xs text-zinc-400 mt-1">Usage allocations and entitlement state available in your workspace.</p></div>
    <Card padding="lg" className="flex flex-col md:flex-row md:items-center justify-between gap-6"><div className="space-y-2"><div className="flex items-center gap-2.5"><h3 className="text-xl font-bold text-zinc-100">Current Subscription</h3><Badge variant="neutral" size="sm">{billing.status.toUpperCase()}</Badge></div><p className="text-xs text-zinc-300 max-w-xl leading-relaxed">Subscription and entitlement details are returned by the billing service.</p></div><div className="text-right shrink-0"><div className="text-2xl font-bold text-zinc-100">{new Intl.NumberFormat(undefined, { style: 'currency', currency: billing.currency || 'USD', maximumFractionDigits: 2 }).format(billing.amount)} <span className="text-xs font-sans text-zinc-400 font-normal">/ month</span></div><div className="text-[11px] text-zinc-500 font-mono mt-0.5">Next renewal: {billing.renewalDate || '—'}</div>{billing.paymentMethod && <div className="text-[11px] text-zinc-400 font-mono mt-1">Card ending in {billing.paymentMethod.last4} ({billing.paymentMethod.brand})</div>}</div></Card>
    <div className="space-y-4"><h3 className="text-xs font-semibold text-zinc-300 uppercase tracking-wider">Workspace Entitlement Consumption</h3><AnimatedGrid className="grid-cols-1 md:grid-cols-2" itemClassName="w-full">{meters.map(([label, v]) => { const percent = meter(v.used, v.total); return <Card key={label} padding="md" className="space-y-2"><div className="flex items-center justify-between text-xs"><span className="text-zinc-300 font-medium">{label}</span><span className="font-mono text-zinc-400">{v.used.toLocaleString()} / {v.total.toLocaleString()}</span></div><AnimatedProgress value={percent} label="Capacity utilized" showValue={false} /><div className="flex items-center justify-between text-[10px] text-zinc-500 font-mono"><span>{percent}% utilized</span><AnimatedNumber value={v.used} className="text-zinc-400" /></div></Card>; })}</AnimatedGrid></div>
  </APEXReveal></div>;
};
