import React, { useEffect, useState } from 'react';
import { formatMoney } from '../currency';
import { Bot, RefreshCw, AlertTriangle, Zap, CheckCircle2 } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../api/client';
import { BrainAuditResponse, WorkflowExecutionLog } from '../types';
import { Card, Button, Badge, Skeleton, AnimatedTabs, AnimatedList, ExpandableCard, APEXReveal, APEXMetric, APEXDynamicIsland, APEXConversation, APEXReasoning, APEXToolCall } from '../components/apex3x';

export const BrainView: React.FC = () => {
  const { addToast, triggerRefresh, refreshKey, currentWorkspace } = useApp();
  const displayCurrency = currentWorkspace?.currency || 'USD';
  const [audit, setAudit] = useState<BrainAuditResponse | null>(null);
  const [logs, setLogs] = useState<WorkflowExecutionLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [scanning, setScanning] = useState(false);
  const [executingId, setExecutingId] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'recommendations' | 'cycle' | 'history'>('recommendations');
  const load = async () => { try { setLoading(true); const [auditRes, logsRes] = await Promise.all([api.getBrainAudit(), api.getWorkflowLogs()]); setAudit(auditRes); setLogs(logsRes); } catch (err) { console.error('Failed fetching brain audit:', err); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [refreshKey]);
  const runScan = async () => { try { setScanning(true); const result = await api.getBrainAudit(); setAudit(result); addToast({ type: 'success', title: 'Autonomous Scan Complete', description: 'Business data loaded.' }); } catch (err) { addToast({ type: 'error', title: 'Scan Failed', description: (err as Error).message }); } finally { setScanning(false); } };
  const executeRecommendation = async (id: string) => { try { setExecutingId(id); const result = await api.executeBrainAction(id); addToast({ type: 'success', title: 'Action Executed', description: result.message }); await load(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Execution Failed', description: (err as Error).message }); } finally { setExecutingId(null); } };
  if (loading || !audit) return <div className="space-y-6"><Skeleton className="h-32" /><Skeleton className="h-24" /><Skeleton className="h-80" /></div>;
  return <div className="space-y-6 pb-12">
    <APEXReveal><section className="relative overflow-hidden rounded-2xl border border-white/[0.10] bg-[#0a0a0e] p-6 lg:p-8"><div className="relative flex flex-col xl:flex-row xl:items-end justify-between gap-7"><div className="max-w-4xl"><div className="flex items-center gap-2"><span className="p-1.5 rounded-lg bg-white/[0.06] text-zinc-200 border border-white/[0.08]"><Bot className="w-5 h-5" /></span><h2 className="text-lg font-bold text-zinc-100">Revenue Audit</h2><APEXDynamicIsland label="BUSINESS AUDIT" value="business audit" /></div><p className="text-xs text-zinc-300 mt-2 max-w-2xl">{audit.headline}</p></div><Button variant="primary" size="md" isLoading={scanning} onClick={runScan} leftIcon={<RefreshCw className="w-4 h-4" />}>Run Audit</Button></div></section></APEXReveal>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Card padding="md"><span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Revenue at Risk</span><APEXMetric value={audit.totalRevenueAtRisk} currency={displayCurrency} className="block text-2xl font-bold text-zinc-100 mt-3" /><p className="text-[11px] text-zinc-400 mt-1">{audit.criticalLeakagesCount} reported operational anomalies</p></Card><Card padding="md"><span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Decide / Act State</span><div className="text-sm font-bold text-zinc-100 mt-3">{audit.autonomousCycle.decide}</div><p className="text-[11px] text-zinc-400 mt-1">Current decision</p></Card><Card padding="md"><span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Learn State</span><div className="text-sm font-bold text-zinc-100 mt-3">{audit.autonomousCycle.learn}</div><p className="text-[11px] text-zinc-400 mt-1">Current learning</p></Card></div>
    <AnimatedTabs tabs={[{ id: 'recommendations', label: 'Recommendations', count: audit.recommendations.length }, { id: 'cycle', label: 'Autonomous Loop' }, { id: 'history', label: 'Execution Log', count: logs.length }]} activeTab={activeTab} onChange={id => setActiveTab(id as typeof activeTab)} />
    {activeTab === 'recommendations' && <APEXConversation>{audit.recommendations.length === 0 ? <Card padding="lg"><p className="text-sm text-zinc-400">No recommendations found.</p></Card> : audit.recommendations.map(rec => <ExpandableCard key={rec.id} title={rec.title} summary={`${rec.severity.toUpperCase()} · $${formatMoney(rec.estimatedRecovery, displayCurrency)} estimated recovery`}><div className="space-y-4"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-2"><div className="flex items-center gap-2"><Badge variant="default" size="sm"><AlertTriangle className="w-3 h-3" /> {rec.severity.toUpperCase()}</Badge><span className="text-xs font-mono px-2 py-0.5 rounded bg-white/[0.05] text-zinc-300 uppercase">{rec.category}</span></div><span className="text-sm font-mono font-bold text-zinc-100">${formatMoney(rec.estimatedRecovery, displayCurrency)} estimated recovery</span></div><p className="text-xs text-zinc-400 leading-relaxed">{rec.rationale}</p><APEXReasoning title="Why APEX selected this decision"><p>{rec.rationale}</p></APEXReasoning><APEXToolCall tool={rec.executablePayload.type} status={executingId === rec.id ? 'running' : 'queued'}>Target: {rec.executablePayload.targetId}</APEXToolCall><div className="p-3.5 rounded-lg bg-[#08080c] border border-white/[0.07]"><div className="text-xs font-medium text-zinc-200 flex items-center gap-2"><Zap className="w-3.5 h-3.5" /> Recommended action</div><p className="text-xs text-zinc-300 mt-2 leading-relaxed">{rec.recommendedAction}</p></div><div className="flex items-center justify-end"><Button variant="primary" size="sm" isLoading={executingId === rec.id} onClick={() => executeRecommendation(rec.id)}>Execute</Button></div></div></ExpandableCard>)}</APEXConversation>}
    {activeTab === 'cycle' && <AnimatedList className="space-y-3">{(['detect', 'understand', 'decide', 'act', 'learn'] as const).map((stage, index) => <Card key={stage} padding="md"><div className="flex items-center justify-between mb-2"><span className="text-xs font-mono font-bold text-zinc-200">{index + 1}. {stage.toUpperCase()}</span><span className="text-[9px] font-mono uppercase text-zinc-600">stage</span></div><p className="text-sm text-zinc-300">{audit.autonomousCycle[stage]}</p></Card>)}</AnimatedList>}
    {activeTab === 'history' && <Card variant="default" padding="none" className="overflow-hidden"><div className="divide-y divide-white/[0.06]">{logs.length === 0 ? <div className="p-6 text-sm text-zinc-500">No execution history available.</div> : logs.map(log => <div key={log.id} className="p-4 flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Badge variant="default" size="sm"><CheckCircle2 className="w-3 h-3" /> {log.status.toUpperCase()}</Badge><span className="text-xs font-medium text-zinc-200">{log.triggerEvent}</span></div><p className="text-xs text-zinc-400 mt-1">{log.details}</p></div><span className="text-[11px] text-zinc-500 font-mono">{new Date(log.executedAt).toLocaleString()}</span></div>)}</div></Card>}
  </div>;
};
