import React, { useEffect, useState } from 'react';
import { Sparkles, RefreshCw, ArrowRight, CheckCircle2, Zap, TrendingDown, TrendingUp } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../api/client';
import { BusinessInsightsData, ActionableInsightRecommendation, NavItemKey } from '../types';
import { Card, Button, Skeleton, EmptyState, AnimatedNumber, AnimatedProgress, AnimatedTabs, AnimatedGrid, ExpandableCard, APEXReveal } from '../components/apex3x';

export const BusinessInsightsView: React.FC = () => {
  const { setActiveNav, addToast } = useApp();
  const [data, setData] = useState<BusinessInsightsData | null>(null); const [loading, setLoading] = useState(true); const [analyzing, setAnalyzing] = useState(false); const [executingId, setExecutingId] = useState<string | null>(null); const [activeTab, setActiveTab] = useState<'all' | 'revenue_loss' | 'predictive_trends' | 'recommendations'>('all');
  const fetchInsights = async (refresh = false) => { try { setLoading(true); setData(await api.getBusinessInsights(refresh)); } catch (err) { addToast({ type: 'error', title: 'Insights Unavailable', description: (err as Error).message }); } finally { setLoading(false); } };
  useEffect(() => { fetchInsights(); }, []);
  const runAnalysis = async () => { try { setAnalyzing(true); setData(await api.triggerInsightsAnalysis()); addToast({ type: 'success', title: 'AI Audit Complete', description: 'Fresh insight telemetry returned by the connected platform.' }); } catch (err) { addToast({ type: 'error', title: 'Audit Failed', description: (err as Error).message }); } finally { setAnalyzing(false); } };
  const execute = async (rec: ActionableInsightRecommendation) => { try { setExecutingId(rec.id); await api.executeInsightAction(rec.id); await fetchInsights(true); addToast({ type: 'success', title: 'Action Executed', description: `Execution recorded for ${rec.title}.` }); } catch (err) { addToast({ type: 'error', title: 'Execution Failed', description: (err as Error).message }); } finally { setExecutingId(null); } };
  const navigate = (target: string) => { const nav: Record<string, NavItemKey> = { leads: 'leads', pipeline: 'pipeline', invoices: 'invoices', marketing: 'marketing', conversations: 'conversations', bookings: 'bookings' }; if (nav[target]) setActiveNav(nav[target]); };

  if (loading) return <div className="space-y-6"><Skeleton className="h-32" /><div className="grid grid-cols-1 md:grid-cols-4 gap-4">{[1,2,3,4].map(i => <Skeleton key={i} className="h-28" />)}</div><Skeleton className="h-80" /></div>;
  if (!data || data.hasSufficientData === false) return <div className="space-y-6 pb-12"><APEXReveal><div className="border-b border-white/[0.08] pb-6"><span className="text-[10px] font-mono uppercase tracking-wide text-zinc-400">Autonomous Revenue Intelligence</span><h1 className="text-2xl sm:text-3xl font-bold text-zinc-100 mt-2">AI-Powered Business Insights</h1><p className="text-sm text-zinc-400 mt-1">Insights are generated only from persisted workspace business data.</p></div><EmptyState icon={<Sparkles className="w-8 h-8" />} title="Insufficient Workspace Telemetry" description={data?.insufficientDataReason || 'No sufficient persisted business data is currently available for verified insights.'} actionLabel="Go to CRM Leads" onAction={() => setActiveNav('leads')} /></APEXReveal></div>;

  const { executiveSummary, revenueLossBreakdown, predictiveTrends, actionableRecommendations, systemVsAiComparison } = data;
  const recoveryRate = executiveSummary.totalRevenueLossIdentified > 0 ? Math.round((executiveSummary.potentialRecoveryAmount / executiveSummary.totalRevenueLossIdentified) * 100) : null;
  const tabs = [{ id: 'all', label: 'All', count: revenueLossBreakdown.length + predictiveTrends.length + actionableRecommendations.length }, { id: 'revenue_loss', label: 'Revenue Leakage', count: revenueLossBreakdown.length }, { id: 'predictive_trends', label: 'Predictive Trends', count: predictiveTrends.length }, { id: 'recommendations', label: 'Recommendations', count: actionableRecommendations.length }];

  return <div className="space-y-8 pb-16"><APEXReveal>
    <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 border-b border-white/[0.08] pb-6"><div><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-mono uppercase tracking-wide text-zinc-400">Autonomous Revenue Intelligence</span><span className="text-zinc-600">•</span><span className="text-[11px] font-mono text-zinc-400">Engine: <strong className="text-zinc-200">{executiveSummary.modelUsed || 'Connected AI provider'}</strong></span><span className="text-zinc-600">•</span><span className="text-[11px] font-mono text-zinc-400">Confidence: <strong className="text-zinc-200">{executiveSummary.aiConfidenceScore}%</strong></span></div><h1 className="text-2xl sm:text-3xl font-bold text-zinc-100 tracking-tight mt-1">AI-Powered Business Insights</h1><p className="text-sm text-zinc-400 mt-1 max-w-3xl">Cross-functional intelligence based on current workspace telemetry returned by the connected platform.</p></div><div className="flex items-center gap-3"><Button variant="primary" size="md" isLoading={analyzing} onClick={runAnalysis} leftIcon={<Sparkles className="w-4 h-4" />}>Run Deep AI Audit</Button><Button variant="secondary" size="md" onClick={() => fetchInsights(true)} leftIcon={<RefreshCw className="w-3.5 h-3.5" />}>Refresh</Button></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Card padding="md"><span className="text-[10px] font-mono uppercase text-zinc-500">Identified Loss</span><AnimatedNumber value={executiveSummary.totalRevenueLossIdentified} prefix="$" className="block text-xl font-bold text-zinc-100 mt-2" /></Card><Card padding="md"><span className="text-[10px] font-mono uppercase text-zinc-500">Potential Recovery</span><AnimatedNumber value={executiveSummary.potentialRecoveryAmount} prefix="$" className="block text-xl font-bold text-zinc-100 mt-2" />{recoveryRate !== null && <span className="text-[10px] text-zinc-400 mt-1 block">{recoveryRate}% of identified loss</span>}</Card><Card padding="md"><span className="text-[10px] font-mono uppercase text-zinc-500">Health Index</span><AnimatedNumber value={executiveSummary.overallHealthIndex} suffix=" / 100" className="block text-xl font-bold text-zinc-100 mt-2" /></Card><Card padding="md"><span className="text-[10px] font-mono uppercase text-zinc-500">AI Confidence</span><AnimatedNumber value={executiveSummary.aiConfidenceScore} suffix="%" className="block text-xl font-bold text-zinc-100 mt-2" /></Card></div>
    <Card variant="elevated" padding="lg"><h2 className="text-lg font-semibold text-zinc-100">{executiveSummary.headline}</h2><p className="text-sm text-zinc-300 mt-2">{executiveSummary.subheadline}</p><div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-5 pt-4 border-t border-white/[0.06]"><div><span className="text-[10px] text-zinc-500">Recorded Loss</span><div className="font-mono text-sm text-zinc-200 mt-1">${systemVsAiComparison.systemRecordedLoss.toLocaleString()}</div></div><div><span className="text-[10px] text-zinc-500">AI Projected Loss</span><div className="font-mono text-sm text-zinc-200 mt-1">${systemVsAiComparison.aiProjectedLossWithChurn.toLocaleString()}</div></div><div><span className="text-[10px] text-zinc-500">Untracked SLA Decay</span><div className="font-mono text-sm text-zinc-200 mt-1">${systemVsAiComparison.untrackedSlaDecay.toLocaleString()}</div></div><div><span className="text-[10px] text-zinc-500">Ad Fatigue Waste</span><div className="font-mono text-sm text-zinc-200 mt-1">${systemVsAiComparison.adFatigueWaste.toLocaleString()}</div></div></div></Card>
    <AnimatedTabs tabs={tabs} activeTab={activeTab} onChange={id => setActiveTab(id as typeof activeTab)} />
    {(activeTab === 'all' || activeTab === 'revenue_loss') && <section className="space-y-4"><h3 className="text-base font-semibold text-zinc-100">Quantified Revenue Leakage</h3>{revenueLossBreakdown.length === 0 ? <Card padding="lg"><p className="text-sm text-zinc-500">No revenue leakage records returned.</p></Card> : <AnimatedGrid className="grid-cols-1 md:grid-cols-2" itemClassName="w-full">{revenueLossBreakdown.map(item => <ExpandableCard key={item.id} title={item.title} summary={`-${item.lostAmount.toLocaleString()} · ${item.department}`}><div className="space-y-3"><p className="text-xs text-zinc-400">{item.rootCause}</p><div className="space-y-1">{item.detectedSignals.map((signal, i) => <div key={i} className="text-xs text-zinc-300">• {signal}</div>)}</div><div className="pt-3 border-t border-white/[0.06] font-mono text-xs text-zinc-300">${item.lostAmount.toLocaleString()} identified loss</div></div></ExpandableCard>)}</AnimatedGrid>}</section>}
    {(activeTab === 'all' || activeTab === 'predictive_trends') && <section className="space-y-4"><h3 className="text-base font-semibold text-zinc-100">Predictive Trends & Forward Outlook</h3>{predictiveTrends.length === 0 ? <Card padding="lg"><p className="text-sm text-zinc-500">No predictive trends returned.</p></Card> : <AnimatedGrid className="grid-cols-1 md:grid-cols-2 lg:grid-cols-4" itemClassName="w-full">{predictiveTrends.map(trend => <Card key={trend.id} padding="md"><div className="flex items-center justify-between"><span className="text-[10px] font-mono text-zinc-400">{trend.timeframe}</span><span className="text-[10px] font-mono text-zinc-400">{trend.aiConfidence}% confidence</span></div><h4 className="text-xs font-semibold text-zinc-200 mt-3">{trend.metric}</h4><div className="flex items-center gap-2 mt-2">{trend.trajectory === 'down' ? <TrendingDown className="w-4 h-4 text-zinc-300" /> : trend.trajectory === 'up' ? <TrendingUp className="w-4 h-4 text-zinc-300" /> : null}<span className="text-sm font-bold text-zinc-100">{trend.projection}</span></div><p className="text-xs text-zinc-400 mt-2">{trend.predictionDetail}</p><AnimatedProgress value={Math.min(100, Math.max(0, trend.aiConfidence))} label="Forecast confidence" showValue={false} className="mt-4" /><div className="flex justify-between mt-4 pt-3 border-t border-white/[0.06] text-[10px] font-mono"><span>{trend.baselineValue}</span><span className="text-zinc-300">{trend.forecastedValue}</span></div></Card>)}</AnimatedGrid>}</section>}
    {(activeTab === 'all' || activeTab === 'recommendations') && <section className="space-y-4"><div className="flex items-center justify-between"><h3 className="text-base font-semibold text-zinc-100">Actionable Recommendations</h3><span className="text-xs text-zinc-500">{actionableRecommendations.filter(r => r.status === 'executed').length} executed / {actionableRecommendations.length}</span></div>{actionableRecommendations.length === 0 ? <Card padding="lg"><p className="text-sm text-zinc-500">No recommendations returned.</p></Card> : <AnimatedGrid className="!grid-cols-1" itemClassName="w-full">{actionableRecommendations.map(rec => <ExpandableCard key={rec.id} title={rec.title} summary={`+$${rec.projectedRecovery.toLocaleString()} projected recovery`}><div className="space-y-3"><div className="text-[10px] font-mono uppercase text-zinc-400">{rec.targetModuleLabel} · {rec.aiConfidence}% confidence</div><p className="text-xs text-zinc-300">{rec.aiRationale}</p><div className="space-y-1">{rec.implementationSteps.map((step, i) => <div key={i} className="text-xs text-zinc-400">{i + 1}. {step}</div>)}</div><div className="flex items-center justify-end gap-2 pt-3 border-t border-white/[0.06]"><Button variant="secondary" size="sm" onClick={() => navigate(rec.targetModule)} rightIcon={<ArrowRight className="w-3 h-3" />}>{rec.actionButtonText}</Button>{rec.status !== 'executed' ? <Button variant="primary" size="sm" isLoading={executingId === rec.id} onClick={() => execute(rec)} leftIcon={<Zap className="w-3 h-3" />}>Execute Decision</Button> : <span className="text-xs text-zinc-300 flex items-center gap-1"><CheckCircle2 className="w-3.5 h-3.5" /> Executed</span>}</div></div></ExpandableCard>)}</AnimatedGrid>}</section>}
  </APEXReveal></div>;
};
