import React, { useEffect, useState } from 'react';
import { MessageSquare, Send, Plus, Sparkles, Search } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../api/client';
import { ConversationThread } from '../types';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { EmptyState } from '../components/ui/EmptyState';
import { Skeleton } from '../components/ui/Skeleton';
import { AnimatedInput, AnimatedList, NotificationBadge, ProgressiveBlur } from '../components/apex3x/adapters';

export const ConversationsView: React.FC = () => {
  const { addToast, refreshKey } = useApp();
  const [threads, setThreads] = useState<ConversationThread[]>([]); const [activeId, setActiveId] = useState<string | null>(null); const [active, setActive] = useState<ConversationThread | null>(null); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [drafting, setDrafting] = useState(false); const [message, setMessage] = useState(''); const [creating, setCreating] = useState(false); const [createOpen, setCreateOpen] = useState(false); const [contactName, setContactName] = useState(''); const [company, setCompany] = useState(''); const [email, setEmail] = useState(''); const [channel, setChannel] = useState<'whatsapp' | 'email' | 'web_chat'>('whatsapp');
  const load = async (preserveId?: string) => { try { setLoading(true); const result = await api.getConversations({ search: search.trim() || undefined }); setThreads(result); const id = preserveId || activeId || result[0]?.id || null; if (id && result.some(t => t.id === id)) { setActiveId(id); setActive(await api.getConversation(id)); } else { setActiveId(null); setActive(null); } } catch (err) { console.error('Failed fetching conversations:', err); } finally { setLoading(false); } }; useEffect(() => { load(); }, [refreshKey]);
  const select = async (id: string) => { try { setActiveId(id); setActive(await api.getConversation(id)); } catch (err) { addToast({ type: 'error', title: 'Conversation Load Failed', description: (err as Error).message }); } };
  const send = async () => { if (!active || !message.trim()) return; try { setSending(true); const sent = await api.sendMessage(active.id, message.trim(), active.channel); setActive({ ...active, messages: [...active.messages, sent], lastMessageSnippet: sent.content, lastMessageAt: sent.timestamp }); setMessage(''); await load(active.id); addToast({ type: 'success', title: 'Message Dispatched', description: 'Message submitted through the connected platform.' }); } catch (err) { addToast({ type: 'error', title: 'Dispatch Failed', description: (err as Error).message }); } finally { setSending(false); } };
  const smartReply = async () => { if (!active) return; try { setDrafting(true); const result = await api.getConversationSmartReply(active.id); setMessage(result.replyText); addToast({ type: 'info', title: 'AI Draft Ready', description: 'Draft returned by the configured AI provider.' }); } catch (err) { addToast({ type: 'error', title: 'AI Draft Failed', description: (err as Error).message }); } finally { setDrafting(false); } };
  const create = async (e: React.FormEvent) => { e.preventDefault(); if (!contactName.trim()) return; try { setCreating(true); const thread = await api.createConversation({ contactName: contactName.trim(), company: company.trim() || undefined, contactEmail: email.trim() || undefined, channel }); setCreateOpen(false); setContactName(''); setCompany(''); setEmail(''); setActiveId(thread.id); await load(thread.id); addToast({ type: 'success', title: 'Conversation Created', description: 'Conversation record created by the connected platform.' }); } catch (err) { addToast({ type: 'error', title: 'Creation Failed', description: (err as Error).message }); } finally { setCreating(false); } };
  const unreadTotal = threads.reduce((sum, thread) => sum + thread.unreadCount, 0);

  return <div className="space-y-6 pb-12">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-lg font-serif-display font-bold text-zinc-100">Unified Communications Inbox</h2><Badge variant="gold" size="sm">{threads.length} Threads</Badge><NotificationBadge count={unreadTotal} /></div><p className="text-xs text-zinc-400 mt-1">Conversation records and outbound actions returned by the connected workspace.</p></div><Button variant="primary" size="sm" onClick={() => setCreateOpen(true)} leftIcon={<Plus className="w-3.5 h-3.5" />}>New Conversation</Button></div>
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-0 h-[680px] bg-[#09090e] border border-white/[0.08] rounded-xl overflow-hidden">
      <div className="lg:col-span-4 border-r border-white/[0.08] flex flex-col bg-[#07070b]"><div className="p-3 border-b border-white/[0.08]"><div className="relative"><Search className="w-3.5 h-3.5 text-zinc-500 absolute left-3 top-1/2 -translate-y-1/2" /><input value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => e.key === 'Enter' && load()} placeholder="Search conversations..." className="w-full bg-[#12121c] border border-white/[0.07] rounded-lg pl-8 pr-3 py-1.5 text-xs text-zinc-200 placeholder-zinc-500 focus:outline-none focus:border-amber-500" /></div></div><div className="flex-1 overflow-y-auto">{loading ? <div className="p-3 space-y-2">{[1,2,3,4].map(i => <Skeleton key={i} className="h-16" />)}</div> : threads.length === 0 ? <div className="p-6 text-center text-xs text-zinc-500">No conversation records returned.</div> : <AnimatedList>{threads.map(thread => <button key={thread.id} onClick={() => select(thread.id)} className={`w-full p-3 text-left border-b border-white/[0.04] ${thread.id === activeId ? 'bg-amber-500/10 border-l-2 border-l-amber-500' : 'hover:bg-white/[0.03]'}`}><div className="flex items-center justify-between gap-2"><span className="text-xs font-semibold text-zinc-200 truncate">{thread.contactName}</span><span className="text-[10px] text-zinc-500">{new Date(thread.lastMessageAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div><p className="text-[11px] text-zinc-400 truncate mt-1">{thread.lastMessageSnippet}</p><div className="flex items-center gap-2 mt-1.5"><span className="text-[9px] uppercase font-mono text-zinc-500">{thread.channel}</span><NotificationBadge count={thread.unreadCount} /></div></button>)}</AnimatedList>}</div></div>
      <div className="lg:col-span-8 flex flex-col bg-[#0b0b12]">{active ? <><div className="p-4 border-b border-white/[0.08] flex items-center justify-between"><div><div className="flex items-center gap-2"><h3 className="text-sm font-semibold text-zinc-100">{active.contactName}</h3><Badge variant="slate" size="sm">{active.channel}</Badge></div><p className="text-[11px] text-zinc-500 mt-1">{active.company || active.contactEmail || active.contactPhone || 'Contact details unavailable'}</p></div><Button variant="ghost" size="sm" onClick={smartReply} isLoading={drafting} leftIcon={<Sparkles className="w-3.5 h-3.5 text-amber-400" />}>Draft Reply</Button></div><ProgressiveBlur edge="bottom" className="flex-1 min-h-0"><div className="overflow-y-auto p-4 space-y-3 h-full">{active.messages.map(msg => <div key={msg.id} className={`flex ${msg.sender === 'agent' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-xl p-3 rounded-xl text-xs ${msg.sender === 'agent' ? 'bg-amber-500/15 border border-amber-500/25 text-zinc-100' : 'bg-[#13131d] border border-white/[0.08] text-zinc-200'}`}><p>{msg.content}</p><span className="block text-[9px] text-zinc-500 mt-1">{new Date(msg.timestamp).toLocaleString()}</span></div></div>)}</div></ProgressiveBlur><div className="p-3 border-t border-white/[0.08] flex gap-2"><AnimatedInput aria-label={`Message via ${active.channel}`} value={message} onChange={e => setMessage(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} placeholder={`Message via ${active.channel}...`} className="py-2" /><Button variant="primary" size="sm" onClick={send} isLoading={sending} disabled={!message.trim()} leftIcon={<Send className="w-3.5 h-3.5" />}>Send</Button></div></> : <div className="flex-1 flex items-center justify-center"><EmptyState icon={<MessageSquare className="w-6 h-6" />} title="No Conversation Selected" description="Select a persisted conversation record to view its messages." /></div>}</div>
    </div>
    {createOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4"><form onSubmit={create} className="w-full max-w-md bg-[#0c0c14] border border-white/[0.12] rounded-xl p-5 space-y-4"><div><h3 className="text-sm font-semibold text-zinc-100">New Conversation</h3><p className="text-[11px] text-zinc-500 mt-1">Create a conversation record through the connected platform.</p></div><AnimatedInput label="Contact name" required placeholder="Contact name" value={contactName} onChange={e => setContactName(e.target.value)} /><AnimatedInput label="Company / organization" placeholder="Company / organization" value={company} onChange={e => setCompany(e.target.value)} /><AnimatedInput label="Email" type="email" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} /><select value={channel} onChange={e => setChannel(e.target.value as typeof channel)} className="w-full bg-[#141420] border border-white/[0.08] rounded-lg px-3 py-2 text-xs text-zinc-100"><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="web_chat">Web Chat</option></select><div className="flex justify-end gap-2 pt-2 border-t border-white/[0.08]"><Button type="button" variant="secondary" size="sm" onClick={() => setCreateOpen(false)}>Cancel</Button><Button type="submit" variant="primary" size="sm" isLoading={creating}>Create</Button></div></form></div>}
  </div>;
};
