import React, { useState, useEffect } from 'react';
import { Building, Search, Mail, Phone, ArrowUpRight } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../api/client';
import { Customer } from '../types';
import { Card, Button, Badge, Skeleton, EmptyState, AnimatedNumber, AnimatedProgress, AnimatedGrid, ExpandableCard, APEXReveal } from '../components/apex3x';

export const CustomersView: React.FC = () => {
  const { setActiveNav, refreshKey } = useApp();
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const fetchCustomers = async () => { try { setLoading(true); setCustomers(await api.getCustomers()); } catch (err) { console.error('Failed fetching customers:', err); } finally { setLoading(false); } };
  useEffect(() => { fetchCustomers(); }, [refreshKey]);
  const filtered = customers.filter(c => c.name.toLowerCase().includes(search.toLowerCase()) || c.company.toLowerCase().includes(search.toLowerCase()) || c.email.toLowerCase().includes(search.toLowerCase()));
  const totalLtv = customers.reduce((acc, c) => acc + c.lifetimeValue, 0);
  const customersWithHealth = customers.filter(c => Number.isFinite(c.healthScore));
  const averageHealth = customersWithHealth.length ? Math.round(customersWithHealth.reduce((acc, c) => acc + c.healthScore, 0) / customersWithHealth.length) : null;
  const activeCustomers = customers.filter(c => c.status === 'active').length;

  return <div className="space-y-6 pb-12"><APEXReveal>
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-lg font-bold text-zinc-100">Customer Intelligence</h2><Badge variant="neutral" size="sm">{customers.length} Accounts</Badge></div><p className="text-xs text-zinc-400 mt-1">Account lifetime value, operational health, engagement and retention signals.</p></div><Button variant="secondary" size="md" onClick={() => setActiveNav('invoices')} leftIcon={<ArrowUpRight className="w-4 h-4" />}>Commercial Billing Ledger</Button></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><Card padding="sm"><span className="text-[11px] font-semibold text-zinc-400 uppercase tracking-wider">Total Customer LTV</span><AnimatedNumber value={totalLtv} prefix="$" className="block text-xl font-bold text-zinc-100 mt-1" /><span className="text-[10px] text-zinc-500">Across connected customer records</span></Card><Card padding="sm"><span className="text-[11px] font-semibold text-zinc-400 uppercase tracking-wider">Average Account Health</span>{averageHealth === null ? <span className="block text-xl font-bold text-zinc-500 mt-1">Not available</span> : <><AnimatedNumber value={averageHealth} suffix="%" className="block text-xl font-bold text-zinc-100 mt-1" /><AnimatedProgress value={averageHealth} showValue={false} className="mt-2" /></>}</Card><Card padding="sm"><span className="text-[11px] font-semibold text-zinc-400 uppercase tracking-wider">Active Accounts</span><AnimatedNumber value={activeCustomers} className="block text-xl font-bold text-zinc-100 mt-1" /><span className="text-[10px] text-zinc-500">Current workspace accounts</span></Card></div>
    <div className="p-3 bg-[#0a0a0f] border border-white/[0.08] rounded-xl flex items-center max-w-md focus-within:border-white/[0.18] transition-colors"><Search className="w-4 h-4 text-zinc-500 mr-2.5 shrink-0" /><input aria-label="Filter customers" type="text" placeholder="Filter customers by name, company, or email..." value={search} onChange={e => setSearch(e.target.value)} className="w-full bg-transparent text-xs text-zinc-200 placeholder-zinc-500 focus:outline-none" /></div>
    {loading ? <div className="space-y-3">{[1,2,3].map(i => <Skeleton key={i} className="h-20" />)}</div> : filtered.length === 0 ? <EmptyState icon={<Building className="w-6 h-6" />} title="No Accounts Found" description={search ? 'No customer accounts match your search filter.' : 'No customer accounts are available for this workspace.'} /> : <AnimatedGrid className="!grid-cols-1" itemClassName="w-full">{filtered.map(cust => <ExpandableCard key={cust.id} title={cust.company} summary={`${cust.name} · ${cust.tier.toUpperCase()} tier · ${cust.status.replace('_', ' ')}`}><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-5"><div className="space-y-2 min-w-0 flex-1"><div className="flex items-center gap-2 flex-wrap"><span className="text-xs text-zinc-400">Primary contact: {cust.name}</span><Badge variant="neutral" size="sm">{cust.tier.toUpperCase()} TIER</Badge><Badge variant="neutral" size="sm">{cust.status.replace('_', ' ')}</Badge></div><div className="flex items-center gap-4 text-xs text-zinc-400 flex-wrap"><span className="flex items-center gap-1.5"><Mail className="w-3.5 h-3.5 text-zinc-500" /> {cust.email}</span><span className="flex items-center gap-1.5"><Phone className="w-3.5 h-3.5 text-zinc-500" /> {cust.phone}</span><span className="text-[11px] text-zinc-500">Joined {new Date(cust.joinedAt).toLocaleDateString()}</span></div><AnimatedProgress value={cust.healthScore} label="Account health" /></div><div className="flex items-center gap-6 shrink-0"><div className="text-right"><span className="text-xs text-zinc-500">Lifetime Value</span><AnimatedNumber value={cust.lifetimeValue} prefix="$" className="block text-base font-mono font-bold text-zinc-100" /></div><Button variant="secondary" size="sm" onClick={() => setActiveNav('conversations')}>Message</Button></div></div></ExpandableCard>)}</AnimatedGrid>}
  </APEXReveal></div>;
};
