import React, { useState, useEffect } from 'react';
import { AlertTriangle, Bot, CheckCircle2, DollarSign, TrendingUp, ShieldCheck, Zap, ChevronRight, Sparkles, Plug } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../api/client';
import { DashboardSummary } from '../types';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { Skeleton } from '../components/ui/Skeleton';
import { AnimatedNumber, AnimatedProgress, ExpandableCard, PinnedList } from '../components/apex3x/adapters';

export const DashboardView: React.FC = () => {
  const { setActiveNav, setConnectDrawerOpen, addToast, triggerRefresh, refreshKey } = useApp();
  const [data, setData] = useState<DashboardSummary | null>(null);
  const [loading, setLoading] = useState(true);
  const [executingId, setExecutingId] = useState<string | null>(null);
  const [pinnedDealIds, setPinnedDealIds] = useState<string[]>([]);

  const fetchDashboard = async () => { try { setLoading(true); setData(await api.getDashboardSummary()); } catch (err) { console.error('Failed fetching dashboard:', err); } finally { setLoading(false); } };
  useEffect(() => { fetchDashboard(); }, [refreshKey]);

  const handleExecuteAction = async (alertId: string) => { try { setExecutingId(alertId); const res = await api.executeBrainAction(alertId); addToast({ type: 'success', title: 'Autonomous Action Executed', description: res.message }); await fetchDashboard(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Execution Failed', description: (err as Error).message }); } finally { setExecutingId(null); } };

  if (loading || !data) return <div className="space-y-6"><div className="grid grid-cols-1 md:grid-cols-4 gap-4">{[1,2,3,4].map(i => <Skeleton key={i} className="h-28" />)}</div><Skeleton className="h-64" /><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><Skeleton className="h-72" /><Skeleton className="h-72" /></div></div>;

  const { metrics, autonomousCycleStatus, pendingAlerts, recentDeals } = data;
  const cycleSteps = [
    { step: '1. DETECT', desc: 'Identify revenue leakage and operational latency', label: `${autonomousCycleStatus.detectedAnomalies} anomaly signals` },
    { step: '2. UNDERSTAND', desc: 'Diagnose operational root cause', label: 'Root-cause analysis' },
    { step: '3. DECIDE', desc: 'Prescribe highest-leverage actions', label: 'Decision state' },
    { step: '4. ACT', desc: 'Dispatch through connected channels', label: 'Dispatch state' },
    { step: '5. LEARN', desc: 'Tune operational parameters from outcomes', label: 'Feedback state' },
  ];
  const dealItems = recentDeals.map(deal => ({ id: deal.id, title: deal.title, meta: `${deal.company} · $${deal.value.toLocaleString()} · ${deal.probability}%`, pinned: pinnedDealIds.includes(deal.id) }));

  return <div className="space-y-6 pb-12">
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 p-5 rounded-xl bg-gradient-to-r from-[#0d0d14] via-[#101018] to-[#0d0d14] border border-amber-500/20 shadow-xl shadow-black/60"><div><div className="flex items-center gap-2"><span className="p-1 rounded bg-amber-500/10 text-amber-400 border border-amber-500/30"><Bot className="w-4 h-4" /></span><h2 className="text-base font-serif-display font-semibold text-zinc-100">Operational Command Center</h2><Badge variant="gold" size="sm">{autonomousCycleStatus.currentPhase || 'Current cycle state'}</Badge></div><p className="text-xs text-zinc-400 mt-1 max-w-2xl">Monitoring workspace telemetry supplied by the connected APEX3X platform.</p></div><div className="flex items-center gap-3"><Button variant="secondary" size="sm" onClick={() => setConnectDrawerOpen(true)} leftIcon={<Plug className="w-3.5 h-3.5 text-amber-400" />}>+ Connect Ecosystem</Button><Button variant="primary" size="sm" onClick={() => setActiveNav('brain')} leftIcon={<Sparkles className="w-3.5 h-3.5" />}>View Brain Diagnostics</Button></div></div>

    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
      <Card variant="gold-accent" padding="md"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Revenue at Risk</span><span className="p-1.5 rounded-lg bg-rose-950/40 text-rose-400 border border-rose-500/30"><AlertTriangle className="w-4 h-4" /></span></div><div className="mt-3"><AnimatedNumber value={metrics.totalRevenueAtRisk} prefix="$" className="text-2xl font-serif-display font-bold text-rose-300" /><div className="flex items-center gap-1.5 mt-1 text-[11px] text-zinc-400"><span className="text-rose-400 font-medium">{autonomousCycleStatus.detectedAnomalies} anomalies</span><span>reported by current telemetry</span></div></div></Card>
      <Card variant="default" padding="md"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Active Pipeline</span><span className="p-1.5 rounded-lg bg-amber-950/30 text-amber-400 border border-amber-500/20"><TrendingUp className="w-4 h-4" /></span></div><div className="mt-3"><AnimatedNumber value={metrics.activePipelineValue} prefix="$" className="text-2xl font-serif-display font-bold text-zinc-100" /><div className="flex items-center gap-1.5 mt-1 text-[11px] text-zinc-400"><span className="text-emerald-400 font-medium">${metrics.wonValueThisMonth.toLocaleString()}</span><span>won this billing cycle</span></div></div></Card>
      <Card variant="default" padding="md"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Overdue Receivables</span><span className="p-1.5 rounded-lg bg-white/[0.05] text-zinc-300 border border-white/[0.08]"><DollarSign className="w-4 h-4" /></span></div><div className="mt-3"><AnimatedNumber value={metrics.overdueReceivables} prefix="$" className="text-2xl font-serif-display font-bold text-amber-300" /><div className="text-[11px] text-zinc-400 mt-1">Current receivables telemetry</div></div></Card>
      <Card variant="default" padding="md"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">System Health</span><span className="p-1.5 rounded-lg bg-emerald-950/30 text-emerald-400 border border-emerald-500/20"><ShieldCheck className="w-4 h-4" /></span></div><div className="mt-3"><AnimatedNumber value={metrics.systemHealth} suffix="%" className="text-2xl font-serif-display font-bold text-emerald-400" /><AnimatedProgress value={metrics.systemHealth} label="Live health signal" showValue={false} className="mt-2" /><div className="text-[11px] text-zinc-400 mt-1">{metrics.connectedIntegrationsCount} connected integrations reported</div></div></Card>
    </div>

    <Card variant="elevated" padding="lg" className="border-amber-500/20"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-white/[0.07]"><div><h3 className="text-sm font-semibold text-zinc-100 uppercase tracking-wider flex items-center gap-2"><Zap className="w-4 h-4 text-amber-400" /> APEX3X Autonomous Operating Cycle</h3><p className="text-xs text-zinc-400 mt-0.5">The operating cycle is represented from current workspace telemetry.</p></div><Badge variant="emerald" size="sm"><CheckCircle2 className="w-3 h-3" /> Recovered ${autonomousCycleStatus.recoveredRevenueMonth.toLocaleString()} this month</Badge></div><div className="grid grid-cols-1 sm:grid-cols-5 gap-3 pt-4">{cycleSteps.map(item => <div key={item.step} className="p-3 rounded-lg border bg-[#0b0b11] border-white/[0.07] space-y-1.5"><div className="flex items-center justify-between"><span className="text-[11px] font-mono font-semibold text-amber-300">{item.step}</span></div><p className="text-[11px] text-zinc-400 leading-snug">{item.desc}</p><p className="text-[10px] font-mono text-zinc-500 pt-1">{item.label}</p></div>)}</div></Card>

    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
      <div className="lg:col-span-7 space-y-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold text-zinc-100 flex items-center gap-2">Immediate Revenue Interventions <span className="text-xs px-2 py-0.5 rounded-full bg-rose-500/20 text-rose-300 font-mono">{pendingAlerts.length}</span></h3><p className="text-xs text-zinc-400 mt-0.5">Operational decisions returned by the connected platform.</p></div><button onClick={() => setActiveNav('brain')} className="text-xs text-amber-400 hover:text-amber-300 font-medium flex items-center gap-1">View Full Diagnostics <ChevronRight className="w-3 h-3" /></button></div><div className="space-y-3">{pendingAlerts.length === 0 ? <Card padding="md"><p className="text-xs text-zinc-500">No pending interventions.</p></Card> : pendingAlerts.map(alert => <ExpandableCard key={alert.id} title={alert.headline} summary={`${alert.severity.toUpperCase()} · $${alert.revenueAtRisk.toLocaleString()} at risk`}><div className="space-y-3"><div className="flex items-center gap-2"><Badge variant="rose" size="sm"><AlertTriangle className="w-3 h-3" /> {alert.severity.toUpperCase()}</Badge><span className="text-[11px] text-zinc-500 font-mono">{new Date(alert.suggestedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div><p className="text-xs text-zinc-300 leading-relaxed">{alert.detectedIssue}</p><div className="p-3 rounded-lg bg-[#07070b] border border-white/[0.06] text-xs text-zinc-300"><span className="text-amber-400 font-medium">Prescribed Action: </span>{alert.recommendedAction}</div><div className="flex justify-end"><Button variant="primary" size="sm" isLoading={executingId === alert.id} onClick={() => handleExecuteAction(alert.id)} leftIcon={<Zap className="w-3.5 h-3.5" />}>Execute Autonomous Decision</Button></div></div></ExpandableCard>)}</div></div>
      <div className="lg:col-span-5 space-y-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold text-zinc-100">Commercial Pipeline</h3><p className="text-xs text-zinc-400 mt-0.5">Deals returned by the connected workspace.</p></div><button onClick={() => setActiveNav('pipeline')} className="text-xs text-amber-400 hover:text-amber-300 font-medium flex items-center gap-1">Pipeline Board <ChevronRight className="w-3 h-3" /></button></div><Card variant="default" padding="md"><PinnedList items={dealItems} onTogglePin={id => setPinnedDealIds(ids => ids.includes(id) ? ids.filter(x => x !== id) : [...ids, id])} renderItem={item => <div><p className="text-xs font-semibold text-zinc-200 truncate">{item.title}</p><p className="text-[10px] text-zinc-500 mt-0.5 truncate">{item.meta}</p></div>} /><div className="pt-3 mt-2 border-t border-white/[0.06] text-center"><Button variant="ghost" size="sm" className="w-full text-xs text-zinc-400" onClick={() => setActiveNav('pipeline')}>View all pipeline stages &rarr;</Button></div></Card></div>
    </div>
  </div>;
};
