import React, { useState, useEffect } from 'react';
import { Plug, RefreshCw, ShieldCheck, Globe2, Webhook, KeyRound, Server } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../api/client';
import { IntegrationConnection } from '../types';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { Skeleton } from '../components/ui/Skeleton';
import { Modal } from '../components/ui/Modal';
import { Input } from '../components/ui/Input';
import { AnimatedGrid, AnimatedNumber } from '../components/apex3x/adapters';
import { UniversalConnector, UniversalConnectionDraft } from '../components/integrations/UniversalConnector';

export const IntegrationsView: React.FC = () => {
  const { addToast, triggerRefresh, refreshKey } = useApp();
  const [integrations, setIntegrations] = useState<IntegrationConnection[]>([]); const [loading, setLoading] = useState(true); const [syncingProvider, setSyncingProvider] = useState<string | null>(null); const [activeConfigureModal, setActiveConfigureModal] = useState<IntegrationConnection | null>(null); const [universalOpen, setUniversalOpen] = useState(false); const [accountName, setAccountName] = useState(''); const [accountId, setAccountId] = useState('');
  const fetchIntegrations = async () => { try { setLoading(true); setIntegrations(await api.getIntegrations()); } catch (err) { console.error('Failed fetching integrations:', err); } finally { setLoading(false); } }; useEffect(() => { fetchIntegrations(); }, [refreshKey]);
  const handleToggle = async (item: IntegrationConnection) => { if (item.status === 'connected') { try { setSyncingProvider(item.provider); await api.disconnectIntegration(item.provider); addToast({ type: 'info', title: `${item.name} Disconnected`, description: 'Provider synchronization paused.' }); await fetchIntegrations(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Disconnection failed', description: (err as Error).message }); } finally { setSyncingProvider(null); } } else { setAccountName(item.connectedAccountName || ''); setAccountId(item.connectedAccountId || ''); setActiveConfigureModal(item); } };
  const handleConnectConfirm = async () => { if (!activeConfigureModal || !accountName.trim() || !accountId.trim()) return; try { setSyncingProvider(activeConfigureModal.provider); await api.connectIntegration(activeConfigureModal.provider, { accountName: accountName.trim(), accountId: accountId.trim() }); addToast({ type: 'success', title: `${activeConfigureModal.name} Connected`, description: 'Connection status updated by the platform.' }); setActiveConfigureModal(null); setAccountName(''); setAccountId(''); await fetchIntegrations(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Connection failed', description: (err as Error).message }); } finally { setSyncingProvider(null); } };
  const handleSync = async (item: IntegrationConnection) => { try { setSyncingProvider(item.provider); await api.syncIntegration(item.provider); addToast({ type: 'success', title: `${item.name} Synchronized`, description: 'Synchronization completed.' }); await fetchIntegrations(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Sync failed', description: (err as Error).message }); } finally { setSyncingProvider(null); } };
  const handleUniversal = async (draft: UniversalConnectionDraft) => { try { await api.connectUniversalIntegration(draft); setUniversalOpen(false); addToast({ type: 'success', title: `${draft.name} Connection Accepted`, description: 'The connected APEX3X platform confirmed the universal connection.' }); await fetchIntegrations(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Universal Connection Not Completed', description: (err as Error).message }); } };
  const connectedCount = integrations.filter(i => i.status === 'connected').length;
  return <div className="space-y-6 pb-12">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-lg font-serif-display font-bold text-zinc-100">Integrations Ecosystem & Connect Hub</h2><Badge variant="gold" size="sm"><AnimatedNumber value={connectedCount} /> / {integrations.length} Active</Badge></div><p className="text-xs text-zinc-400 mt-1">Connect the services your business already owns — native providers, OAuth accounts, APIs, webhooks, custom HTTP endpoints, and MCP.</p></div><Button variant="primary" size="md" onClick={() => setUniversalOpen(true)} leftIcon={<Globe2 className="w-4 h-4" />}>Connect</Button></div>
    <Card variant="elevated" padding="lg" className="border-white/20"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-5"><div className="min-w-0"><div className="flex items-center gap-2"><Globe2 className="w-5 h-5 text-zinc-200" /><h3 className="text-sm font-semibold text-zinc-100">Universal Connection Layer</h3></div><p className="text-xs text-zinc-400 mt-1 max-w-3xl leading-relaxed">APEX3X is not a closed catalog. A service can be connected through the protocol it actually exposes. WhatsApp/Meta, Facebook, Instagram, Google, ad managers, CRMs, commerce tools, internal systems, webhooks, and future providers all use the same workspace-scoped connection surface.</p></div><div className="flex flex-wrap gap-2 shrink-0"><span className="text-[10px] px-2 py-1 rounded-full bg-white/[0.05] text-zinc-400"><KeyRound className="inline w-3 h-3 mr-1" />API</span><span className="text-[10px] px-2 py-1 rounded-full bg-white/[0.05] text-zinc-400"><Webhook className="inline w-3 h-3 mr-1" />Webhook</span><span className="text-[10px] px-2 py-1 rounded-full bg-white/[0.05] text-zinc-400"><Server className="inline w-3 h-3 mr-1" />MCP</span></div></div></Card>
    {loading ? <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{[1,2,3,4,5,6].map(i => <Skeleton key={i} className="h-56" />)}</div> : integrations.length === 0 ? <Card padding="lg"><p className="text-xs text-zinc-500">No integration records are available for this workspace. Use Connect to configure the first customer-owned connection.</p></Card> : <AnimatedGrid>{integrations.map(item => { const isConn = item.status === 'connected'; const isOperating = syncingProvider === item.provider; return <Card key={item.id} variant={isConn ? 'default' : 'sunken'} padding="lg" className="space-y-4 transition-all flex flex-col justify-between"><div className="space-y-3"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><h3 className="text-sm font-semibold text-zinc-100">{item.name}</h3><Badge variant={isConn ? 'emerald' : item.status === 'pending' ? 'amber' : 'slate'} size="sm">{isConn ? 'Connected' : item.status === 'pending' ? 'Pending' : 'Disconnected'}</Badge></div><span className="text-[10px] text-zinc-500 uppercase tracking-wider font-mono">{item.category}{item.connectionMethod ? ` · ${item.connectionMethod}` : ''}</span></div><span className="p-2 rounded-lg bg-[#14141e] border border-white/[0.08] text-zinc-200"><Plug className="w-4 h-4" /></span></div>{item.connectedAccountName ? <div className="p-2.5 rounded-lg bg-[#08080c] border border-white/[0.05] space-y-0.5 text-xs"><div className="text-[11px] font-medium text-zinc-300 truncate">Account: {item.connectedAccountName}</div>{item.connectedAccountId && <div className="text-[10px] font-mono text-zinc-500 truncate">ID: {item.connectedAccountId}</div>}</div> : <div className="p-2.5 rounded-lg bg-[#08080c] border border-white/[0.04] text-[11px] text-zinc-500">Not connected.</div>}<div className="space-y-1.5"><span className="text-[11px] font-medium text-zinc-400">Capabilities:</span><div className="flex flex-wrap gap-1">{item.capabilities.map((cap, idx) => <span key={idx} className="text-[10px] px-2 py-0.5 rounded bg-white/[0.04] text-zinc-300 border border-white/[0.05]">{cap}</span>)}</div></div></div><div className="pt-4 border-t border-white/[0.06] flex items-center justify-between"><span className="text-[10px] text-zinc-500 font-mono">{item.lastSyncedAt ? `Synced ${new Date(item.lastSyncedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : 'No sync recorded'}</span><div className="flex items-center gap-2">{isConn && <Button variant="ghost" size="sm" isLoading={isOperating} onClick={() => handleSync(item)} title="Sync now"><RefreshCw className="w-3.5 h-3.5" /></Button>}<Button variant={isConn ? 'outline' : 'primary'} size="sm" isLoading={isOperating} onClick={() => handleToggle(item)}>{isConn ? 'Disconnect' : '+ Connect'}</Button></div></div></Card>; })}</AnimatedGrid>}
    {activeConfigureModal && <Modal isOpen={!!activeConfigureModal} onClose={() => setActiveConfigureModal(null)} title={`+ Connect ${activeConfigureModal.name}`} subtitle="Enter the provider account identity required by the connected platform."><div className="space-y-4"><Input label="Account Identity / Display Name" value={accountName} onChange={e => setAccountName(e.target.value)} placeholder="Provider account name" required /><Input label="Provider Account ID / Handle" value={accountId} onChange={e => setAccountId(e.target.value)} placeholder="Provider account identifier" required /><div className="p-3.5 rounded-lg bg-[#08080c] border border-white/20 text-xs text-zinc-300 space-y-1"><span className="text-zinc-200 font-medium flex items-center gap-1.5"><ShieldCheck className="w-3.5 h-3.5" /> Connection Scope</span><p className="text-[11px] text-zinc-400 leading-relaxed">Requested capabilities: {activeConfigureModal.capabilities.join(', ')}.</p></div><div className="flex justify-end gap-3 pt-3 border-t border-white/[0.08]"><Button variant="secondary" size="md" onClick={() => setActiveConfigureModal(null)}>Cancel</Button><Button variant="primary" size="md" onClick={handleConnectConfirm} disabled={!accountName.trim() || !accountId.trim()}>Connect</Button></div></div></Modal>}
    <UniversalConnector open={universalOpen} onClose={() => setUniversalOpen(false)} onSubmit={handleUniversal} />
  </div>;
};
