import React, { useState, useEffect } from 'react';
import { Users, Plus, Search, AlertTriangle, Phone, Mail, UserCheck } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../api/client';
import { Lead } from '../types';
import { formatMoney } from '../currency';
import { Card, Button, Badge, Modal, Input, Select, Skeleton, EmptyState, AnimatedNumber, AnimatedProgress, AnimatedGrid, ExpandableCard, APEXReveal } from '../components/apex3x';

export const LeadsView: React.FC = () => {
  const { addToast, triggerRefresh, refreshKey, currentWorkspace } = useApp();
  const currency = currentWorkspace?.currency;
  const [leads, setLeads] = useState<Lead[]>([]); const [loading, setLoading] = useState(true); const [searchQuery, setSearchQuery] = useState(''); const [statusFilter, setStatusFilter] = useState('all'); const [isCreateOpen, setIsCreateOpen] = useState(false); const [actionInProgress, setActionInProgress] = useState<string | null>(null); const [formName, setFormName] = useState(''); const [formEmail, setFormEmail] = useState(''); const [formPhone, setFormPhone] = useState(''); const [formCompany, setFormCompany] = useState(''); const [formSource, setFormSource] = useState<'website_form' | 'google_ads' | 'meta_ads' | 'whatsapp' | 'referral'>('website_form'); const [formValue, setFormValue] = useState(''); const [formNotes, setFormNotes] = useState('');
  const fetchLeads = async () => { try { setLoading(true); setLeads(await api.getLeads()); } catch (err) { console.error('Failed fetching leads:', err); } finally { setLoading(false); } }; useEffect(() => { fetchLeads(); }, [refreshKey]);
  const handleCreateLead = async () => { if (!formName) return; try { setActionInProgress('create'); const payload: Partial<Lead> = { name: formName, email: formEmail, phone: formPhone, company: formCompany, source: formSource, notes: formNotes }; if (formValue.trim()) payload.estimatedValue = Number(formValue); const newLead = await api.createLead(payload); addToast({ type: 'success', title: 'Lead Created', description: `${newLead.name} (${newLead.company}) added to active triage.` }); setIsCreateOpen(false); setFormName(''); setFormEmail(''); setFormPhone(''); setFormCompany(''); setFormValue(''); setFormNotes(''); await fetchLeads(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Failed creating lead', description: (err as Error).message }); } finally { setActionInProgress(null); } };
  const handleQualify = async (leadId: string, leadName: string) => { try { setActionInProgress(leadId); await api.qualifyLead(leadId); addToast({ type: 'success', title: 'Lead Qualified', description: `${leadName} qualified.` }); await fetchLeads(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Qualification failed', description: (err as Error).message }); } finally { setActionInProgress(null); } };
  const handleConvert = async (leadId: string, leadName: string) => { try { setActionInProgress(leadId); await api.convertLead(leadId); addToast({ type: 'success', title: 'Lead Converted to Customer', description: `${leadName} converted to an active customer.` }); await fetchLeads(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Conversion failed', description: (err as Error).message }); } finally { setActionInProgress(null); } };
  const filteredLeads = leads.filter(l => { const q = searchQuery.toLowerCase(); return (l.name.toLowerCase().includes(q) || l.company.toLowerCase().includes(q) || l.email.toLowerCase().includes(q)) && (statusFilter === 'all' || l.status === statusFilter); });
  const totalValue = filteredLeads.reduce((acc, l) => acc + l.estimatedValue, 0); const highRiskCount = filteredLeads.filter(l => l.leakRisk === 'high').length; const scoredLeads = filteredLeads.filter(l => Number.isFinite(l.score)); const averageScore = scoredLeads.length ? Math.round(scoredLeads.reduce((acc, l) => acc + l.score, 0) / scoredLeads.length) : null;
  return <div className="space-y-6 pb-12"><APEXReveal>
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-lg font-bold text-zinc-100">CRM & Qualified Leads</h2><Badge variant="neutral" size="sm">{leads.length} Tracked</Badge></div><p className="text-xs text-zinc-400 mt-1">Qualification scoring, inbound attribution, and response-decay signals from workspace data.</p></div><Button variant="primary" size="md" onClick={() => setIsCreateOpen(true)} leftIcon={<Plus className="w-4 h-4" />}>Add Inbound Lead</Button></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><Card variant="default" padding="sm"><span className="text-[11px] font-semibold text-zinc-400 uppercase tracking-wider">Total Inbound Value</span><div className="block text-xl font-bold text-zinc-100 mt-1">{formatMoney(totalValue, currency)}</div></Card><Card variant="default" padding="sm"><span className="text-[11px] font-semibold text-zinc-400 uppercase tracking-wider">High Leak Risk Leads</span><AnimatedNumber value={highRiskCount} className="block text-xl font-bold text-zinc-100 mt-1" /><span className="text-xs font-sans text-zinc-400 font-normal">{highRiskCount > 0 ? 'Requires SLA intervention' : 'No current high-risk signal'}</span></Card><Card variant="default" padding="sm"><span className="text-[11px] font-semibold text-zinc-400 uppercase tracking-wider">Avg Lead Qualification Score</span>{averageScore === null ? <span className="block text-xl font-bold text-zinc-500 mt-1">Not available</span> : <AnimatedNumber value={averageScore} suffix=" / 100" className="block text-xl font-bold text-zinc-100 mt-1" />}</Card></div>
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-3 bg-[#0a0a0f] border border-white/[0.08] rounded-xl"><div className="relative flex-1 max-w-md"><Search className="w-4 h-4 text-zinc-500 absolute left-3 top-1/2 -translate-y-1/2" /><input type="text" placeholder="Search leads by contact name, company, or email..." value={searchQuery} onChange={e => setSearchQuery(e.target.value)} className="w-full bg-[#0e0e16] border border-white/[0.08] rounded-lg pl-9 pr-4 py-1.5 text-xs text-zinc-200 placeholder-zinc-500 focus:outline-none focus:border-white/40" /></div><Select value={statusFilter} onChange={e => setStatusFilter(e.target.value)} options={[{ value: 'all', label: 'All Statuses' }, { value: 'new', label: 'New Inbounds' }, { value: 'contacted', label: 'Contacted' }, { value: 'qualifying', label: 'Qualifying' }, { value: 'qualified', label: 'Qualified' }, { value: 'converted', label: 'Converted' }]} className="py-1.5 text-xs" /></div>
    {loading ? <div className="space-y-3">{[1,2,3,4].map(i => <Skeleton key={i} className="h-20" />)}</div> : filteredLeads.length === 0 ? <EmptyState icon={<Users className="w-6 h-6" />} title="No Leads Found" description="No inbound inquiries match the selected criteria." actionLabel="Create Inbound Lead" onAction={() => setIsCreateOpen(true)} /> : <AnimatedGrid className="!grid-cols-1" itemClassName="w-full">{filteredLeads.map(lead => { const isHighRisk = lead.leakRisk === 'high'; return <ExpandableCard key={lead.id} title={`${lead.name} · ${lead.company}`} summary={`${lead.status.toUpperCase()} · ${lead.source.replace('_', ' ')} · ${formatMoney(lead.estimatedValue, currency)}` }><div className="space-y-4"><div className="flex flex-wrap items-center gap-2"><Badge variant="neutral" size="sm">{lead.status.toUpperCase()}</Badge>{isHighRisk && <Badge variant="neutral" size="sm"><AlertTriangle className="w-3 h-3" /> SLA DECAY RISK</Badge>}<span className="text-[10px] text-zinc-500 font-mono">Inbound source: {lead.source.replace('_', ' ')}</span></div><div className="flex items-center gap-4 text-xs text-zinc-400 flex-wrap"><span className="flex items-center gap-1.5"><Mail className="w-3.5 h-3.5 text-zinc-500" /> {lead.email}</span><span className="flex items-center gap-1.5"><Phone className="w-3.5 h-3.5 text-zinc-500" /> {lead.phone}</span></div>{lead.leakReason && <p className="text-xs text-zinc-400 font-mono">Anomaly Reason: {lead.leakReason}</p>}<div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><AnimatedProgress value={lead.score} label="Qualification score" /><div><span className="text-[10px] text-zinc-500">Estimated value</span><div className="block text-base font-mono font-bold text-zinc-100 mt-1">{formatMoney(lead.estimatedValue, currency)}</div></div></div><div className="flex flex-wrap items-center justify-between gap-3 pt-3 border-t border-white/[0.06]"><span className="text-[10px] text-zinc-500">Last contact: {new Date(lead.lastContactAt).toLocaleString()}</span><div className="flex items-center gap-2">{lead.status !== 'qualified' && lead.status !== 'converted' && <Button variant="secondary" size="sm" isLoading={actionInProgress === lead.id} onClick={() => handleQualify(lead.id, lead.name)}>Qualify</Button>}{lead.status === 'qualified' && <Button variant="primary" size="sm" isLoading={actionInProgress === lead.id} onClick={() => handleConvert(lead.id, lead.name)} leftIcon={<UserCheck className="w-3.5 h-3.5" />}>Convert to Customer</Button>}</div></div></div></ExpandableCard>; })}</AnimatedGrid>}
    <Modal isOpen={isCreateOpen} onClose={() => setIsCreateOpen(false)} title="Add Inbound Lead" subtitle="Record prospective buyer information to initiate qualification and routing."><div className="space-y-4"><Input label="Full Contact Name" placeholder="Contact name" value={formName} onChange={e => setFormName(e.target.value)} required /><div className="grid grid-cols-2 gap-3"><Input label="Work Email" type="email" placeholder="name@company.com" value={formEmail} onChange={e => setFormEmail(e.target.value)} /><Input label="Phone Number" placeholder="Phone number" value={formPhone} onChange={e => setFormPhone(e.target.value)} /></div><Input label="Company / Organization" placeholder="Company name" value={formCompany} onChange={e => setFormCompany(e.target.value)} /><div className="grid grid-cols-2 gap-3"><Select label="Acquisition Channel" value={formSource} onChange={e => setFormSource(e.target.value as any)} options={[{ value: 'website_form', label: 'Website Inbound Form' }, { value: 'google_ads', label: 'Google Search Ads' }, { value: 'meta_ads', label: 'Meta B2B Ads' }, { value: 'whatsapp', label: 'WhatsApp Inbound' }, { value: 'referral', label: 'Partner Referral' }]} /><Input label="Estimated Deal Value" type="number" placeholder="Optional" value={formValue} onChange={e => setFormValue(e.target.value)} /></div><Input label="Initial Inbound Notes" placeholder="Notes" value={formNotes} onChange={e => setFormNotes(e.target.value)} /><div className="flex justify-end gap-3 pt-3 border-t border-white/[0.08]"><Button variant="secondary" size="md" onClick={() => setIsCreateOpen(false)}>Cancel</Button><Button variant="primary" size="md" isLoading={actionInProgress === 'create'} onClick={handleCreateLead}>Save & Route Lead</Button></div></div></Modal>
    </APEXReveal></div>;
};
