import React, { useState, useEffect } from 'react';
import { TrendingUp, Star } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../api/client';
import { MarketingOverview } from '../types';
import { Card, Button, Badge, Skeleton, AnimatedNumber, AnimatedProgress, AnimatedGrid, APEXReveal } from '../components/apex3x';

export const MarketingView: React.FC = () => {
  const { setConnectDrawerOpen, refreshKey } = useApp();
  const [data, setData] = useState<MarketingOverview | null>(null); const [loading, setLoading] = useState(true);
  const fetchMarketing = async () => { try { setLoading(true); setData(await api.getMarketingOverview()); } catch (err) { console.error('Failed fetching marketing overview:', err); } finally { setLoading(false); } };
  useEffect(() => { fetchMarketing(); }, [refreshKey]);
  if (loading || !data) return <div className="space-y-6"><Skeleton className="h-32" /><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Skeleton className="h-64" /><Skeleton className="h-64" /></div></div>;
  const { googleAds, metaAds, googleBusinessProfile, channelAttribution } = data;
  return <div className="space-y-6 pb-12"><APEXReveal>
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-lg font-bold text-zinc-100">Marketing</h2><Badge variant="neutral" size="sm">Connected Data</Badge></div><p className="text-xs text-zinc-400 mt-1">Advertising and business-profile metrics available in your workspace.</p></div><Button variant="secondary" size="md" onClick={() => setConnectDrawerOpen(true)}>Manage Ad Connections</Button></div>
    <AnimatedGrid className="grid-cols-1 lg:grid-cols-3" itemClassName="w-full">
      <Card padding="lg" className="space-y-4"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-zinc-100">Google Search Ads</h3><Badge variant="neutral" size="sm">Data Available</Badge></div><div className="grid grid-cols-2 gap-3 p-3 rounded-lg bg-[#07070b] border border-white/[0.05]"><div><span className="text-[10px] text-zinc-500 uppercase tracking-wider">Monthly Spend</span><AnimatedNumber value={googleAds.monthlySpend} prefix="$" className="block text-base font-mono font-bold text-zinc-200 mt-0.5" /></div><div><span className="text-[10px] text-zinc-500 uppercase tracking-wider">Conversions</span><AnimatedNumber value={googleAds.conversions} suffix=" Leads" className="block text-base font-mono font-bold text-zinc-200 mt-0.5" /></div></div><div className="space-y-2 pt-2"><span className="text-xs font-semibold text-zinc-300">Campaign Health</span>{googleAds.campaigns.length === 0 ? <p className="text-xs text-zinc-500">No campaign data available.</p> : googleAds.campaigns.map((camp, idx) => <div key={idx} className="p-2.5 rounded-lg border border-white/[0.06] bg-[#0a0a10] text-xs flex items-center justify-between"><div className="min-w-0 pr-2"><p className="text-xs font-medium text-zinc-200 truncate">{camp.name}</p><span className="text-[10px] text-zinc-500 font-mono">Spend: ${camp.spend.toLocaleString()} · ROAS: {camp.roas}x</span></div><Badge variant="neutral" size="sm">{camp.status === 'leaking' ? 'Leak' : `${camp.conversions} conv`}</Badge></div>)}</div></Card>
      <Card padding="lg" className="space-y-4"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-zinc-100">Meta Ads</h3><Badge variant="neutral" size="sm">Data Available</Badge></div><div className="grid grid-cols-2 gap-3 p-3 rounded-lg bg-[#07070b] border border-white/[0.05]"><div><span className="text-[10px] text-zinc-500 uppercase tracking-wider">Monthly Spend</span><AnimatedNumber value={metaAds.monthlySpend} prefix="$" className="block text-base font-mono font-bold text-zinc-200 mt-0.5" /></div><div><span className="text-[10px] text-zinc-500 uppercase tracking-wider">Leads Generated</span><AnimatedNumber value={metaAds.leadsGenerated} suffix=" Leads" className="block text-base font-mono font-bold text-zinc-200 mt-0.5" /></div></div><div className="p-3 rounded-lg bg-[#0a0a10] border border-white/[0.06] space-y-1.5 text-xs"><div className="text-zinc-400">Cost Per Lead (CPL)</div><AnimatedNumber value={metaAds.costPerLead} prefix="$" decimals={2} className="block text-sm font-mono font-bold text-zinc-100" /><div className="text-[11px] text-zinc-500 pt-1">Top Creative: <span className="text-zinc-300">{metaAds.topCreative || ''}</span></div></div></Card>
      <Card padding="lg" className="space-y-4"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-zinc-100">Google Business Profile</h3><Badge variant="neutral" size="sm">Data Available</Badge></div><div className="grid grid-cols-2 gap-3 p-3 rounded-lg bg-[#07070b] border border-white/[0.05]"><div><span className="text-[10px] text-zinc-500 uppercase tracking-wider">Search Views</span><AnimatedNumber value={googleBusinessProfile.searchViews} className="block text-base font-mono font-bold text-zinc-200 mt-0.5" /></div><div><span className="text-[10px] text-zinc-500 uppercase tracking-wider">Direct Calls</span><AnimatedNumber value={googleBusinessProfile.directCalls} suffix=" Calls" className="block text-base font-mono font-bold text-zinc-200 mt-0.5" /></div></div><div className="p-3 rounded-lg bg-[#0a0a10] border border-white/[0.06]"><div className="text-xs font-medium text-zinc-200">{googleBusinessProfile.locationName || 'Business profile'}</div>{googleBusinessProfile.rating > 0 && <div className="flex items-center gap-1 text-zinc-300 text-[11px] mt-0.5"><Star className="w-3 h-3" /><span>{googleBusinessProfile.rating} Rating ({googleBusinessProfile.reviewsCount} reviews)</span></div>}</div></Card>
    </AnimatedGrid>
    <Card variant="improved" padding="none" className="overflow-hidden"><div className="p-4 border-b border-white/[0.08] bg-[#09090d] flex items-center justify-between"><h3 className="text-xs font-semibold text-zinc-200 uppercase tracking-wider">Multi-Channel Revenue Attribution</h3><span className="text-xs text-zinc-500">Connected service data</span></div><div className="divide-y divide-white/[0.06]">{channelAttribution.length === 0 ? <div className="p-6 text-xs text-zinc-500">No attribution data available.</div> : channelAttribution.map((item, idx) => <div key={idx} className="p-4 flex items-center justify-between hover:bg-white/[0.02]"><div><span className="text-sm font-semibold text-zinc-100">{item.channel}</span><div className="text-xs text-zinc-500 mt-0.5 font-mono">Monthly Spend: ${item.spend.toLocaleString()}</div></div><div className="flex items-center gap-8 text-right"><div><span className="text-[10px] text-zinc-500 uppercase">Attributed Revenue</span><AnimatedNumber value={item.revenue} prefix="$" className="block text-sm font-mono font-bold text-zinc-100" /></div><div><span className="text-[10px] text-zinc-500 uppercase">ROAS</span><span className="block text-sm font-mono font-bold text-zinc-200">{item.roas}x</span></div><Badge variant="neutral" size="sm">{item.leakRisk === 'medium' ? 'Auditing ROAS' : 'Healthy'}</Badge></div></div>)}</div></Card>
  </APEXReveal></div>;
};
