import React, { useState, useEffect } from 'react';
import { Plus, ChevronRight } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../api/client';
import { PipelineDeal } from '../types';
import { formatMoney } from '../currency';
import { Card, Button, Badge, Modal, Input, Select, Skeleton, AnimatedNumber, AnimatedProgress, AnimatedGrid, APEXReveal } from '../components/apex3x';

const STAGES: { id: PipelineDeal['stage']; label: string }[] = [
  { id: 'discovery', label: 'Discovery' }, { id: 'qualified', label: 'Qualified' }, { id: 'proposal_sent', label: 'Proposal Sent' }, { id: 'negotiation', label: 'Negotiation' }, { id: 'closed_won', label: 'Closed Won' },
];

export const PipelineView: React.FC = () => {
  const { currentWorkspace, addToast, triggerRefresh, refreshKey } = useApp();
  const [deals, setDeals] = useState<PipelineDeal[]>([]); const [loading, setLoading] = useState(true); const [isCreateOpen, setIsCreateOpen] = useState(false); const [movingDealId, setMovingDealId] = useState<string | null>(null);
  const currency = currentWorkspace?.currency;
  const [title, setTitle] = useState(''); const [company, setCompany] = useState(''); const [customerName, setCustomerName] = useState(''); const [value, setValue] = useState(''); const [stage, setStage] = useState<PipelineDeal['stage']>('discovery'); const [closeDate, setCloseDate] = useState('');
  const fetchDeals = async () => { try { setLoading(true); setDeals(await api.getDeals()); } catch (err) { console.error('Failed fetching pipeline deals:', err); } finally { setLoading(false); } };
  useEffect(() => { fetchDeals(); }, [refreshKey]);
  const handleCreateDeal = async () => { const numericValue = Number(value); if (!title || !company || !Number.isFinite(numericValue) || numericValue <= 0) return; try { await api.createDeal({ title, company, customerName, value: numericValue, stage, expectedCloseDate: closeDate }); addToast({ type: 'success', title: 'Deal Created', description: `${title} added to pipeline.` }); setIsCreateOpen(false); setTitle(''); setCompany(''); setCustomerName(''); setValue(''); setCloseDate(''); await fetchDeals(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Deal creation failed', description: (err as Error).message }); } };
  const handleAdvanceStage = async (dealId: string, currentStage: PipelineDeal['stage']) => { const stageOrder: PipelineDeal['stage'][] = ['discovery', 'qualified', 'proposal_sent', 'negotiation', 'closed_won']; const currentIndex = stageOrder.indexOf(currentStage); if (currentIndex < stageOrder.length - 1) { const nextStage = stageOrder[currentIndex + 1]; try { setMovingDealId(dealId); await api.moveDealStage(dealId, nextStage); addToast({ type: 'success', title: 'Deal Advanced', description: `Progressed to ${nextStage.replace('_', ' ').toUpperCase()}.` }); await fetchDeals(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Update failed', description: (err as Error).message }); } finally { setMovingDealId(null); } } };
  const totalPipelineValue = deals.filter(d => d.stage !== 'closed_won' && d.stage !== 'closed_lost').reduce((acc, d) => acc + d.value, 0); const wonTotal = deals.filter(d => d.stage === 'closed_won').reduce((acc, d) => acc + d.value, 0); const activeCount = deals.filter(d => d.stage !== 'closed_won' && d.stage !== 'closed_lost').length;

  return <div className="space-y-6 pb-12"><APEXReveal>
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-lg font-bold text-zinc-100">Sales Pipeline & Deal Velocity</h2><Badge variant="neutral" size="sm">{formatMoney(totalPipelineValue, currency)} Active</Badge></div><p className="text-xs text-zinc-400 mt-1">Track deals, values and stages in your pipeline.</p></div><Button variant="primary" size="md" onClick={() => setIsCreateOpen(true)} leftIcon={<Plus className="w-4 h-4" />}>Create Commercial Deal</Button></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><Card padding="sm"><span className="text-[11px] font-semibold text-zinc-400 uppercase tracking-wider">Active Deal Volume</span><AnimatedNumber value={totalPipelineValue}  className="block text-xl font-bold text-zinc-100 mt-1" /></Card><Card padding="sm"><span className="text-[11px] font-semibold text-zinc-400 uppercase tracking-wider">Closed Won</span><AnimatedNumber value={wonTotal}  className="block text-xl font-bold text-zinc-100 mt-1" /></Card><Card padding="sm"><span className="text-[11px] font-semibold text-zinc-400 uppercase tracking-wider">Active Deals</span><AnimatedNumber value={activeCount} className="block text-xl font-bold text-zinc-100 mt-1" /></Card></div>
    {loading ? <div className="grid grid-cols-1 md:grid-cols-5 gap-4">{[1,2,3,4,5].map(i => <Skeleton key={i} className="h-96" />)}</div> : <div className="overflow-x-auto pb-4"><div className="grid grid-cols-5 gap-4 min-w-[1100px]">{STAGES.map(st => { const stageDeals = deals.filter(d => d.stage === st.id); const stageValue = stageDeals.reduce((acc, d) => acc + d.value, 0); return <div key={st.id} className="flex flex-col rounded-xl bg-[#09090e] border border-white/[0.07] p-3 space-y-3 min-h-[500px]"><div className="flex items-center justify-between pb-2 border-b border-white/[0.06]"><div><h3 className="text-xs font-semibold text-zinc-200 uppercase tracking-wider">{st.label}</h3><span className="text-[11px] text-zinc-400 font-mono">{formatMoney(stageValue, currency)}</span></div><span className="text-xs font-mono px-1.5 py-0.2 rounded bg-white/[0.05] text-zinc-400">{stageDeals.length}</span></div><div className="space-y-3 flex-1 overflow-y-auto"><AnimatedGrid className="!grid-cols-1" itemClassName="w-full">{stageDeals.map(deal => <Card key={deal.id} variant="elevated" padding="sm" className="border-white/[0.09] space-y-2.5"><div><h4 className="text-xs font-semibold text-zinc-100">{deal.title}</h4><p className="text-[11px] text-zinc-400">{deal.company}</p></div><div className="flex items-center justify-between pt-1 text-xs"><span className="font-mono font-bold text-zinc-100">{formatMoney(deal.value, currency)}</span><span className="text-[10px] text-zinc-500 font-mono">{deal.probability}% win</span></div><AnimatedProgress value={deal.probability} label="Win probability" showValue={false} /><div className="flex items-center justify-between text-[10px] text-zinc-500 font-mono pt-1 border-t border-white/[0.05]"><span>{deal.assignedTo}</span><span>{deal.expectedCloseDate}</span></div>{deal.stage !== 'closed_won' && <div className="pt-1"><Button variant="secondary" size="sm" isLoading={movingDealId === deal.id} onClick={() => handleAdvanceStage(deal.id, deal.stage)} className="w-full text-[10px] py-1 justify-between" rightIcon={<ChevronRight className="w-3 h-3" />}>Advance</Button></div>}</Card>)}{stageDeals.length === 0 && <div className="py-12 text-center text-xs text-zinc-600 font-mono">Empty Stage</div>}</AnimatedGrid></div></div>; })}</div></div>}
    <Modal isOpen={isCreateOpen} onClose={() => setIsCreateOpen(false)} title="Create Commercial Deal" subtitle="Add the deal details and expected close date."><div className="space-y-4"><Input label="Deal Title" placeholder="Enter deal title" value={title} onChange={e => setTitle(e.target.value)} required /><div className="grid grid-cols-2 gap-3"><Input label="Company Name" placeholder="Enter company name" value={company} onChange={e => setCompany(e.target.value)} required /><Input label="Primary Contact" placeholder="Enter contact name" value={customerName} onChange={e => setCustomerName(e.target.value)} /></div><div className="grid grid-cols-2 gap-3"><Input label="Deal Value" type="number" value={value} onChange={e => setValue(e.target.value)} required /><Select label="Initial Stage" value={stage} onChange={e => setStage(e.target.value as PipelineDeal['stage'])} options={[{ value: 'discovery', label: 'Discovery' }, { value: 'qualified', label: 'Qualified' }, { value: 'proposal_sent', label: 'Proposal Sent' }, { value: 'negotiation', label: 'Negotiation' }]} /></div><Input label="Target Close Date" type="date" value={closeDate} onChange={e => setCloseDate(e.target.value)} /><div className="flex justify-end gap-3 pt-3 border-t border-white/[0.08]"><Button variant="secondary" size="md" onClick={() => setIsCreateOpen(false)}>Cancel</Button><Button variant="primary" size="md" onClick={handleCreateDeal}>Create Pipeline Deal</Button></div></div></Modal>
  </APEXReveal></div>;
};
