import React, { useEffect, useMemo, useState } from 'react';
import { Check, Shield, UserPlus, X } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../api/client';
import { User, SecurityAuditRecord } from '../types';
import { APEX_ROLE_DESCRIPTIONS, APEXRole, PermissionAction, PermissionResource, effectivePermissions } from '../security/permissions';
import { Card, Button, Badge, Modal, Input, Select, Skeleton, AnimatedTabs, AnimatedGrid, APEXReveal } from '../components/apex3x';

const ROLE_OPTIONS: { value: APEXRole; label: string }[] = [
  { value: 'owner', label: 'Workspace Owner' }, { value: 'admin', label: 'Workspace Admin' }, { value: 'manager', label: 'Manager' }, { value: 'operator', label: 'Operator' },
  { value: 'specialist', label: 'Specialist' }, { value: 'marketing', label: 'Marketing' }, { value: 'sales', label: 'Sales' }, { value: 'finance', label: 'Finance' }, { value: 'support', label: 'Support' }, { value: 'viewer', label: 'Viewer' },
];

export const TeamSecurityView: React.FC = () => {
  const { activeNav, addToast, triggerRefresh, refreshKey } = useApp();
  const [members, setMembers] = useState<User[]>([]); const [auditLogs, setAuditLogs] = useState<SecurityAuditRecord[]>([]); const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'members' | 'permissions' | 'audit'>(activeNav === 'security' ? 'audit' : 'members'); const [selectedMemberId, setSelectedMemberId] = useState<string | null>(null);
  const [isInviteOpen, setIsInviteOpen] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [role, setRole] = useState<APEXRole>('operator');
  const fetchData = async () => { try { setLoading(true); const [membersRes, logsRes] = await Promise.all([api.getTeam(), api.getSecurityAudit()]); setMembers(membersRes); setAuditLogs(logsRes); } catch (err) { console.error('Failed fetching team/security data:', err); } finally { setLoading(false); } };
  useEffect(() => { fetchData(); }, [refreshKey]); useEffect(() => { if (activeNav === 'security') setActiveTab('audit'); else if (activeNav === 'team') setActiveTab('members'); }, [activeNav]);
  const selectedMember = members.find(member => member.id === selectedMemberId) ?? members[0] ?? null;
  const permissions = useMemo(() => effectivePermissions(selectedMember), [selectedMember]);
  const resourceRows = Object.entries(permissions) as [PermissionResource, PermissionAction[] | undefined][];
  const handleInvite = async () => { if (!name || !email) return; try { await api.inviteTeamMember({ name, email, role }); addToast({ type: 'success', title: 'Invitation dispatched', description: `Invitation sent to ${email}.` }); setIsInviteOpen(false); setName(''); setEmail(''); await fetchData(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Invite failed', description: (err as Error).message }); } };

  return <div className="space-y-6 pb-12"><APEXReveal>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-lg font-semibold">{activeNav === 'security' ? 'Security & Audit' : 'Team & Permissions'}</h1><Badge variant="neutral" size="sm">{activeNav === 'security' ? 'Audit' : 'Access control'}</Badge></div><p className="mt-1 max-w-2xl text-xs leading-5 text-[var(--text-secondary)]">Access is role-based and evaluated with resource, action, scope and policy. The frontend reflects effective access; protected resources remain server-authorized.</p></div>{activeNav !== 'security' && <Button variant="primary" size="md" onClick={() => setIsInviteOpen(true)} leftIcon={<UserPlus className="size-4" />}>Invite member</Button>}</div>
    <AnimatedTabs tabs={[{ id: 'members', label: 'Team members', count: members.length, icon: <Shield className="size-3.5" /> }, { id: 'permissions', label: 'Effective access' }, { id: 'audit', label: 'Security & Audit', count: auditLogs.length }]} activeTab={activeTab} onChange={id => setActiveTab(id as typeof activeTab)} />
    {activeTab === 'members' && (loading ? <div className="space-y-3">{[1,2,3].map(i => <Skeleton key={i} className="h-20" />)}</div> : members.length === 0 ? <Card padding="lg"><p className="text-sm text-[var(--text-secondary)]">No team members returned by the connected workspace.</p></Card> : <AnimatedGrid className="!grid-cols-1" itemClassName="w-full">{members.map(member => <button key={member.id} type="button" onClick={() => { setSelectedMemberId(member.id); setActiveTab('permissions'); }} className="text-left outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)] rounded-xl"><Card padding="md" className="transition-colors hover:bg-[var(--surface-2)]"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2.5"><h2 className="text-sm font-semibold">{member.name}</h2><Badge variant="neutral" size="sm">{member.role.replace('_', ' ')}</Badge></div><div className="mt-1 text-xs text-[var(--text-secondary)] font-mono">{member.email}</div></div><span className="text-[10px] text-[var(--text-muted)]">View effective access →</span></div></Card></button>)}</AnimatedGrid>)}
    {activeTab === 'permissions' && <div className="grid gap-4 lg:grid-cols-[18rem_1fr]"><Card padding="sm"><p className="px-2 py-2 text-[10px] font-medium text-[var(--text-muted)]">Team member</p><div className="space-y-1">{members.map(member => <button key={member.id} type="button" onClick={() => setSelectedMemberId(member.id)} className={`w-full rounded-lg px-2.5 py-2 text-left outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)] ${selectedMember?.id === member.id ? 'bg-[var(--surface-2)]' : 'hover:bg-[var(--surface-2)]'}`}><span className="block text-xs font-medium">{member.name}</span><span className="mt-0.5 block text-[10px] text-[var(--text-muted)]">{member.role.replace('_', ' ')}</span></button>)}</div></Card><Card padding="lg">{selectedMember ? <><div className="flex flex-col gap-2 border-b border-[var(--border)] pb-4 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-sm font-semibold">{selectedMember.name}</h2><p className="mt-1 text-xs text-[var(--text-secondary)]">{APEX_ROLE_DESCRIPTIONS[selectedMember.role]}</p></div><Badge variant="neutral" size="sm">Scope: workspace membership</Badge></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead><tr className="border-b border-[var(--border)] text-[10px] text-[var(--text-muted)]"><th className="px-2 py-2 font-medium">Resource</th><th className="px-2 py-2 font-medium">View</th><th className="px-2 py-2 font-medium">Create</th><th className="px-2 py-2 font-medium">Update</th><th className="px-2 py-2 font-medium">High-impact</th><th className="px-2 py-2 font-medium">Actions</th></tr></thead><tbody>{resourceRows.map(([resource, actions]) => { const list = actions ?? []; const high = ['publish','execute','approve','refund','disconnect'].filter(action => list.includes(action as PermissionAction)); return <tr key={resource} className="border-b border-[var(--border-subtle)]"><td className="px-2 py-2 text-xs">{resource.replaceAll('_', ' ')}</td><td className="px-2 py-2">{list.includes('view') ? <Check className="size-3.5" /> : <X className="size-3.5 text-[var(--text-muted)]" />}</td><td className="px-2 py-2">{list.includes('create') ? <Check className="size-3.5" /> : <X className="size-3.5 text-[var(--text-muted)]" />}</td><td className="px-2 py-2">{list.includes('update') ? <Check className="size-3.5" /> : <X className="size-3.5 text-[var(--text-muted)]" />}</td><td className="px-2 py-2 text-[10px] text-[var(--text-secondary)]">{high.length ? high.join(', ') : 'None'}</td><td className="px-2 py-2 text-[10px] text-[var(--text-muted)]">{list.length ? list.join(' · ') : 'No access'}</td></tr>; })}</tbody></table></div></> : <p className="text-sm text-[var(--text-secondary)]">Select a team member to inspect effective access.</p>}</Card></div>}
    {activeTab === 'audit' && <Card padding="none" className="overflow-hidden"><div className="border-b border-[var(--border)] px-4 py-3"><h2 className="text-xs font-semibold">Immutable security and authorization history</h2><p className="mt-0.5 text-[10px] text-[var(--text-muted)]">Records returned by the connected workspace. The frontend does not create or alter audit history.</p></div><div className="divide-y divide-[var(--border-subtle)]">{loading ? <div className="p-6"><Skeleton className="h-20" /></div> : auditLogs.length === 0 ? <div className="p-6 text-sm text-[var(--text-secondary)]">No security audit records returned by the connected workspace.</div> : auditLogs.map(log => <div key={log.id} className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="space-y-1"><div className="flex items-center gap-2"><Badge variant="neutral" size="sm">{log.action}</Badge><span className="text-xs font-medium">{log.userName}</span></div><p className="text-xs text-[var(--text-secondary)]">{log.category}</p></div><div className="text-left text-[10px] font-mono text-[var(--text-muted)] sm:text-right"><div>{new Date(log.timestamp).toLocaleString()}</div><div>{log.ipAddress}</div></div></div>)}</div></Card>}
    <Modal isOpen={isInviteOpen} onClose={() => setIsInviteOpen(false)} title="Invite team member" subtitle="Assign an explicit role. Resource scope and action authorization remain policy-controlled."><div className="space-y-4"><Input label="Full name" placeholder="Name" value={name} onChange={e => setName(e.target.value)} required /><Input label="Work email" type="email" placeholder="name@company.com" value={email} onChange={e => setEmail(e.target.value)} required /><Select label="Role" value={role} onChange={e => setRole(e.target.value as APEXRole)} options={ROLE_OPTIONS} /><div className="rounded-lg border border-[var(--border)] bg-[var(--surface)] p-3 text-xs leading-5 text-[var(--text-secondary)]">{APEX_ROLE_DESCRIPTIONS[role]}</div><div className="flex justify-end gap-3 border-t border-[var(--border)] pt-3"><Button variant="secondary" size="md" onClick={() => setIsInviteOpen(false)}>Cancel</Button><Button variant="primary" size="md" onClick={handleInvite}>Send invitation</Button></div></div></Modal>
  </APEXReveal></div>;
};
