import React, { useState, useEffect } from 'react';
import { Zap, Play } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../api/client';
import { WorkflowRule, WorkflowExecutionLog } from '../types';
import { Card, Button, Badge, Skeleton, AnimatedNumber, AnimatedProgress, AnimatedToggle, AnimatedTabs, AnimatedGrid, APEXReveal } from '../components/apex3x';

export const WorkflowsView: React.FC = () => {
  const { addToast, triggerRefresh, refreshKey } = useApp(); const [workflows, setWorkflows] = useState<WorkflowRule[]>([]); const [logs, setLogs] = useState<WorkflowExecutionLog[]>([]); const [loading, setLoading] = useState(true); const [activeTab, setActiveTab] = useState<'rules' | 'logs'>('rules'); const [testingId, setTestingId] = useState<string | null>(null);
  const fetchData = async () => { try { setLoading(true); const [wfRes, logsRes] = await Promise.all([api.getWorkflows(), api.getWorkflowLogs()]); setWorkflows(wfRes); setLogs(logsRes); } catch (err) { console.error('Failed fetching workflows:', err); } finally { setLoading(false); } }; useEffect(() => { fetchData(); }, [refreshKey]);
  const handleToggle = async (id: string, title: string) => { try { const updated = await api.toggleWorkflow(id); addToast({ type: 'info', title: updated.isActive ? 'Workflow Activated' : 'Workflow Paused', description: `"${title}" status updated.` }); await fetchData(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Toggle failed', description: (err as Error).message }); } };
  const handleTestRun = async (id: string) => { try { setTestingId(id); const res = await api.testWorkflow(id); addToast({ type: 'success', title: 'Workflow Test Completed', description: res.message }); await fetchData(); triggerRefresh(); } catch (err) { addToast({ type: 'error', title: 'Test failed', description: (err as Error).message }); } finally { setTestingId(null); } };
  return <div className="space-y-6 pb-12"><APEXReveal>
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-lg font-bold text-zinc-100">Automation Workspace</h2><Badge variant="neutral" size="sm"><AnimatedNumber value={workflows.filter(w => w.isActive).length} /> Active Rules</Badge></div><p className="text-xs text-zinc-400 mt-1">See what APEX automates, review activity, and manage your business rules.</p></div></div>
    <AnimatedTabs tabs={[{ id: 'rules', label: 'Workflows & Rules', count: workflows.length, icon: <Zap className="w-3.5 h-3.5" /> }, { id: 'logs', label: 'Execution History', count: logs.length }]} activeTab={activeTab} onChange={id => setActiveTab(id as typeof activeTab)} />
    {activeTab === 'rules' && (loading ? <div className="space-y-3">{[1,2,3].map(i => <Skeleton key={i} className="h-28" />)}</div> : workflows.length === 0 ? <Card padding="lg"><p className="text-sm text-zinc-500">No workflow rules available.</p></Card> : <AnimatedGrid className="!grid-cols-1" itemClassName="w-full">{workflows.map(wf => <Card key={wf.id} padding="lg" className="space-y-3"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2.5 flex-wrap"><h3 className="text-sm font-semibold text-zinc-100">{wf.title}</h3><Badge variant="neutral" size="sm">{wf.isActive ? 'ACTIVE' : 'PAUSED'}</Badge><span className="text-[10px] font-mono px-2 py-0.5 rounded bg-white/[0.04] text-zinc-400">Trigger: {wf.triggerEvent}</span></div><p className="text-xs text-zinc-400 mt-1 leading-relaxed">Condition: {wf.conditionSummary}</p></div><div className="flex items-center gap-4"><AnimatedToggle checked={wf.isActive} onChange={() => handleToggle(wf.id, wf.title)} label="" /><Button variant="secondary" size="sm" isLoading={testingId === wf.id} onClick={() => handleTestRun(wf.id)} leftIcon={<Play className="w-3 h-3" />}>Test Run</Button></div></div><div className="p-3 rounded-lg bg-[#08080c] border border-white/[0.05] space-y-2 text-xs"><div className="flex items-center justify-between gap-3"><div><span className="text-zinc-300 font-medium">Action: </span><span className="text-zinc-300">{wf.actionSummary}</span></div><span className="text-[11px] font-mono text-zinc-500"><AnimatedNumber value={wf.totalExecutions} /> runs · {wf.successRate}% success</span></div><AnimatedProgress value={wf.successRate} label="Success rate" /></div></Card>)}</AnimatedGrid>)}
    {activeTab === 'logs' && <Card padding="none" className="overflow-hidden"><div className="divide-y divide-white/[0.06]">{loading ? <div className="p-6"><Skeleton className="h-20" /></div> : logs.length === 0 ? <div className="p-6 text-sm text-zinc-500">No execution history available.</div> : logs.map(log => <div key={log.id} className="p-4 flex items-center justify-between gap-4"><div className="space-y-1"><div className="flex items-center gap-2"><Badge variant="neutral" size="sm">{log.status.toUpperCase()}</Badge><span className="text-xs font-semibold text-zinc-200">{log.triggerEvent}</span></div><p className="text-xs text-zinc-400">{log.details}</p></div><span className="text-[11px] text-zinc-500 font-mono whitespace-nowrap">{new Date(log.executedAt).toLocaleString()}</span></div>)}</div></Card>}
  </APEXReveal></div>;
};
