import React, { useEffect, useRef, useState } from "react";
import { ChevronDown } from "lucide-react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
export interface APEX3XNavigationSection { title: string; items: { key: string; label: string; icon: React.ReactNode; badge?: string }[]; }
interface NavigationMenuProps { sections: APEX3XNavigationSection[]; activeKey: string; onSelect: (key: string) => void; }
export const NavigationMenu: React.FC<NavigationMenuProps> = ({ sections, activeKey, onSelect }) => {
 const [open,setOpen]=useState(false); const reducedMotion=useReducedMotion(); const rootRef=useRef<HTMLDivElement>(null); const triggerRef=useRef<HTMLButtonElement>(null); const panelId="apex3x-navigation-disclosure"; const activeLabel=sections.flatMap(s=>s.items).find(i=>i.key===activeKey)?.label||activeKey.replace("_"," ");
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!rootRef.current?.contains(e.target as Node))setOpen(false)};const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);triggerRef.current?.focus()}};document.addEventListener("pointerdown",outside);document.addEventListener("keydown",key);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",key)}},[open]);
 return <div ref={rootRef} className="relative"><button ref={triggerRef} type="button" aria-expanded={open} aria-controls={panelId} onClick={()=>setOpen(v=>!v)} className="group flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface-2)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)]"><span className="capitalize">{activeLabel}</span><motion.span aria-hidden="true" animate={reducedMotion?undefined:{rotate:open?180:0}} transition={{duration:.18}}><ChevronDown className="h-3.5 w-3.5 text-[var(--text-muted)]"/></motion.span></button>
 <AnimatePresence>{open&&<motion.div id={panelId} initial={reducedMotion?undefined:{opacity:0,y:-6,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={reducedMotion?undefined:{opacity:0,y:-4,scale:.98}} transition={reducedMotion?{duration:0}:{duration:.16,ease:"easeOut"}} className="absolute left-0 top-full z-40 mt-2 w-[min(28rem,calc(100vw-2rem))] rounded-xl border border-[var(--border)] bg-[var(--surface-2)] p-2 shadow-2xl shadow-black/40"><nav aria-label="Application navigation"><div className="grid gap-1 sm:grid-cols-2">{sections.map(section=><div key={section.title} className="p-1"><p className="px-2 py-1 text-[9px] font-semibold tracking-[0.12em] text-[var(--text-muted)]">{section.title}</p><div className="space-y-0.5">{section.items.map(item=>{const active=item.key===activeKey;return <button key={item.key} type="button" onClick={()=>{onSelect(item.key);setOpen(false)}} aria-current={active?"page":undefined} className={"relative flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-left text-[11px] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring-brand)] "+(active?"text-[var(--text-primary)]":"text-[var(--text-secondary)] hover:text-[var(--text-primary)]")}><span aria-hidden="true" className="relative z-10 shrink-0 text-[var(--text-muted)]">{item.icon}</span><span className="relative z-10 truncate">{item.label}</span>{item.badge&&<span className="relative z-10 ml-auto rounded-full border border-[var(--border)] bg-[var(--surface)] px-1.5 py-0.5 text-[9px] font-mono text-[var(--text-muted)]">{item.badge}</span>}</button>})}</div></div>)}</div></nav></motion.div>}</AnimatePresence></div>;
};