export type NavItemKey =
  | 'dashboard'
  | 'unified_inbox'
  | 'campaigns' | 'advertising' | 'creatives' | 'social' | 'forms' | 'growth'
  | 'leads' | 'qualified_leads' | 'customers'
  | 'bookings' | 'calendar'
  | 'pipeline' | 'orders' | 'invoices' | 'revenue'
  | 'workflows' | 'rules' | 'tasks' | 'automation_runs'
  | 'integrations' | 'ai_hub'
  | 'team' | 'security' | 'billing' | 'workspace_settings'
  | 'brain' | 'insights' | 'marketing';

export interface Workspace { id: string; name: string; slug: string; industry: string; website: string; currency: string; timezone: string; verificationStatus: 'verified' | 'in_review' | 'unverified'; taxId?: string; registeredAddress?: string; createdAt: string; }
export interface User { id: string; email: string; name: string; role: 'platform_owner' | 'owner' | 'admin' | 'manager' | 'operator' | 'specialist' | 'marketing' | 'sales' | 'finance' | 'support' | 'viewer'; workspaceId: string; avatarUrl?: string; }
export interface Lead { id: string; workspaceId: string; name: string; email: string; phone: string; company: string; source: 'google_ads' | 'meta_ads' | 'website_form' | 'whatsapp' | 'referral' | 'outbound'; status: 'new' | 'contacted' | 'qualifying' | 'qualified' | 'converted' | 'lost'; estimatedValue: number; score: number; leakRisk: 'high' | 'medium' | 'low'; leakReason?: string; lastContactAt: string; createdAt: string; assignedTo: string; notes: string; }
export interface Customer { id: string; workspaceId: string; name: string; email: string; phone: string; company: string; tier: 'starter' | 'growth' | 'enterprise'; lifetimeValue: number; healthScore: number; status: 'active' | 'at_risk' | 'churned'; joinedAt: string; lastActiveAt: string; industry: string; }
export interface ConversationMessage { id: string; conversationId: string; sender: 'customer' | 'agent' | 'system' | 'ai'; senderName: string; content: string; channel: 'whatsapp' | 'email' | 'web_chat' | 'internal' | 'sms'; timestamp: string; status: 'sent' | 'delivered' | 'read' | 'failed'; }
export interface ConversationThread { id: string; workspaceId: string; contactName: string; contactEmail: string; contactPhone: string; company?: string; customerId?: string; channel: 'whatsapp' | 'email' | 'web_chat' | 'omnichannel' | 'sms'; unreadCount: number; lastMessageSnippet: string; lastMessageAt: string; status: 'open' | 'pending' | 'resolved'; priority?: 'high' | 'normal' | 'low'; tags?: string[]; messages: ConversationMessage[]; }
export interface Appointment { id: string; workspaceId: string; title: string; customerName: string; customerEmail: string; customerPhone: string; scheduledAt: string; durationMinutes: number; status: 'confirmed' | 'pending' | 'completed' | 'cancelled'; serviceType: string; assignedStaff: string; notes?: string; }
export interface PipelineDeal { id: string; workspaceId: string; title: string; customerName: string; company: string; value: number; stage: 'discovery' | 'qualified' | 'proposal_sent' | 'negotiation' | 'closed_won' | 'closed_lost'; probability: number; expectedCloseDate: string; assignedTo: string; updatedAt: string; }
export interface Invoice { id: string; workspaceId: string; invoiceNumber: string; customerName: string; customerEmail: string; amount: number; currency: string; status: 'draft' | 'sent' | 'paid' | 'overdue' | 'in_collection'; issueDate: string; dueDate: string; paidAt?: string; collectionAttempts: number; lastReminderSentAt?: string; items: { description: string; quantity: number; unitPrice: number; }[]; }
export interface WebsiteForm { id: string; workspaceId: string; title: string; slug: string; fields: { id: string; label: string; type: 'text' | 'email' | 'phone' | 'textarea' | 'select'; required: boolean; options?: string[]; }[]; submitButtonText: string; successMessage: string; submissionsCount: number; conversionRate: number; isActive: boolean; }
export interface WorkflowRule { id: string; workspaceId: string; title: string; triggerEvent: 'lead_captured' | 'payment_overdue' | 'booking_confirmed' | 'revenue_leak_detected' | 'deal_stalled'; conditionSummary: string; actionSummary: string; actionType: 'send_whatsapp' | 'send_email' | 'create_task' | 'escalate_alert' | 'update_pipeline'; isActive: boolean; totalExecutions: number; lastExecutedAt?: string; successRate: number; }
export interface WorkflowExecutionLog { id: string; workflowId: string; workspaceId: string; triggerEvent: string; status: 'success' | 'failed' | 'running'; details: string; executedAt: string; recoveredValue?: number; }
export interface IntegrationConnection { id: string; workspaceId: string; provider: string; name: string; category: 'advertising' | 'communication' | 'payment' | 'reputation' | 'crm' | 'commerce' | 'storage' | 'productivity' | 'developer' | 'database' | 'other'; status: 'connected' | 'disconnected' | 'error' | 'syncing' | 'pending'; connectionMethod?: 'oauth2' | 'api_key' | 'basic_auth' | 'webhook' | 'custom_http' | 'mcp' | 'native'; connectedAccountName?: string; connectedAccountId?: string; lastSyncedAt?: string; capabilities: string[]; errorDetails?: string; }
export interface AIProviderConfig { id: string; workspaceId: string; provider: 'gemini' | 'openai' | 'anthropic' | 'custom_openai'; name: string; status: 'connected' | 'not_configured' | 'error'; modelSelected: string; hasCustomKey: boolean; maskedKey?: string; endpointUrl?: string; lastTestedAt?: string; latencyMs?: number; }
export interface AutonomousAlert { id: string; workspaceId: string; stage: 'detect' | 'understand' | 'decide' | 'act' | 'learn'; severity: 'critical' | 'warning' | 'info'; category: 'unresponsive_lead' | 'overdue_receivable' | 'ad_spend_leak' | 'calendar_noshow' | 'pipeline_stall'; headline: string; detectedIssue: string; revenueAtRisk: number; recommendedAction: string; executionStatus: 'pending_approval' | 'executed' | 'dismissed'; suggestedAt: string; executedAt?: string; }
export interface SecurityAuditRecord { id: string; workspaceId: string; userId: string; userName: string; action: string; category: 'auth' | 'data_export' | 'integration' | 'ai_config' | 'financial'; ipAddress: string; timestamp: string; }
export interface BillingEntitlement { planTier: 'starter' | 'growth' | 'enterprise'; status: 'active' | 'past_due' | 'trialing'; renewalDate: string; amount: number; currency: string; limits: { leadsMonthly: { used: number; total: number }; automations: { used: number; total: number }; connectedIntegrations: { used: number; total: number }; aiRuns: { used: number; total: number }; }; paymentMethod: { brand: string; last4: string; expiry: string; }; }
export interface DashboardSummary { workspace: Workspace; metrics: { totalRevenueAtRisk: number; activePipelineValue: number; wonValueThisMonth: number; overdueReceivables: number; activeCustomersCount: number; openLeadsCount: number; systemHealth: number; connectedIntegrationsCount: number; }; autonomousCycleStatus: { currentPhase: string; detectedAnomalies: number; recoveredRevenueMonth: number; }; pendingAlerts: AutonomousAlert[]; recentDeals: PipelineDeal[]; }
export interface BrainAuditResponse { headline: string; totalRevenueAtRisk: number; criticalLeakagesCount: number; autonomousCycle: { detect: string; understand: string; decide: string; act: string; learn: string; }; recommendations: Array<{ id: string; category: 'lead' | 'invoice' | 'marketing' | 'booking' | 'pipeline'; severity: 'critical' | 'warning' | 'info'; title: string; rationale: string; estimatedRecovery: number; recommendedAction: string; executablePayload: { type: 'send_whatsapp' | 'escalate_invoice' | 'reassign_lead' | 'pause_ad_group' | 'schedule_followup'; targetId: string; parameters: Record<string, any>; }; }>; }
export interface MarketingOverview { googleAds: { accountName: string; monthlySpend: number; impressions: number; clicks: number; avgCpc: number; conversions: number; costPerConversion: number; lostRoasOpportunity: number; campaigns: Array<{ name: string; spend: number; conversions: number; roas: number; status: 'healthy' | 'leaking'; }>; }; metaAds: { accountName: string; monthlySpend: number; impressions: number; clicks: number; leadsGenerated: number; costPerLead: number; topCreative: string; }; googleBusinessProfile: { locationName: string; searchViews: number; directCalls: number; directionRequests: number; rating: number; reviewsCount: number; }; channelAttribution: Array<{ channel: string; spend: number; revenue: number; roas: number; leakRisk: 'high' | 'medium' | 'low'; }>; }
export interface RevenueLossItem { id: string; category: 'crm_leads' | 'sales_pipeline' | 'receivables' | 'marketing_ads' | 'calendar_noshows'; title: string; department: string; lostAmount: number; rootCause: string; urgency: 'critical' | 'high' | 'medium'; impactPercentage: number; detectedSignals: string[]; }
export interface PredictiveTrend { id: string; metric: string; projection: string; trajectory: 'up' | 'down' | 'stagnant'; timeframe: 'Next 14 Days' | 'Next 30 Days' | 'Quarterly Q4' | 'Annual FY27'; predictionDetail: string; aiConfidence: number; baselineValue: string; forecastedValue: string; riskFactor: 'high' | 'medium' | 'low'; }
export interface ActionableInsightRecommendation { id: string; title: string; targetModule: 'pipeline' | 'invoices' | 'leads' | 'marketing' | 'conversations' | 'bookings'; targetModuleLabel: string; actionButtonText: string; aiRationale: string; projectedRecovery: number; aiConfidence: number; urgency: 'immediate' | 'high_priority' | 'strategic'; implementationSteps: string[]; status: 'recommended' | 'in_progress' | 'executed'; lastEvaluatedAt: string; aiModelSignature: string; }
export interface BusinessInsightsData { hasSufficientData?: boolean; insufficientDataReason?: string; executiveSummary: { headline: string; subheadline: string; totalRevenueLossIdentified: number; potentialRecoveryAmount: number; overallHealthIndex: number; trendOutlook: 'favorable' | 'cautious' | 'critical_remedy'; aiConfidenceScore: number; modelUsed: string; lastGeneratedAt: string; }; revenueLossBreakdown: RevenueLossItem[]; predictiveTrends: PredictiveTrend[]; actionableRecommendations: ActionableInsightRecommendation[]; systemVsAiComparison: { systemRecordedLoss: number; aiProjectedLossWithChurn: number; untrackedSlaDecay: number; adFatigueWaste: number; }; }
